defmodule Autolaunch.Repo.Migrations.StockSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :chain_id, :bigint, null: false
      add :address, :text, null: false
      add :symbol, :text, null: false
      add :name, :text, null: false
      add :search_words, {:array, :text}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:stocks, [:chain_id, :address], name: "stocks_chain_address_index")
  end

  def down do
    drop_if_exists unique_index(:stocks, [:chain_id, :address],
                     name: "stocks_chain_address_index"
                   )

    drop table(:stocks)
  end
end
