defmodule Autolaunch.Repo.Migrations.Accounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:x_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :x_user_id, :text
      add :username, :text
      add :display_name, :text
      add :avatar_url, :text
      add :verified_at, :utc_datetime_usec
      add :attempt_state, :text
      add :attempt_verifier, :text
      add :attempt_generation, :uuid
      add :attempt_expires_at, :utc_datetime_usec
      add :intent_sequence, :bigint
      add :intent_generation, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id, :bigint, null: false
    end

    create unique_index(:x_connections, [:human_account_id, :role],
             name: "x_connections_one_role_per_human_index"
           )

    create table(:session_authorities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :lineage_digest, :binary, null: false
      add :generation, :bigint, null: false, default: 0
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id, :bigint
    end

    create unique_index(:session_authorities, [:lineage_digest],
             name: "session_authorities_unique_lineage_digest_index"
           )

    create table(:linked_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :subject, :text, null: false
      add :username, :text
      add :display_name, :text
      add :verified_at, :utc_datetime_usec, null: false
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id, :bigint, null: false
    end

    create unique_index(:linked_identities, [:provider, :human_account_id],
             name: "linked_identities_unique_provider_per_account_index"
           )

    create unique_index(:linked_identities, [:provider, :subject],
             name: "linked_identities_unique_subject_per_provider_index"
           )

    create table(:human_accounts, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:x_connections) do
      modify :human_account_id,
             references(:human_accounts,
               column: :id,
               name: "x_connections_human_account_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:session_authorities) do
      modify :human_account_id,
             references(:human_accounts,
               column: :id,
               name: "session_authorities_human_account_id_fkey",
               type: :bigint,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:linked_identities) do
      modify :human_account_id,
             references(:human_accounts,
               column: :id,
               name: "linked_identities_human_account_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    alter table(:human_accounts) do
      add :privy_user_id, :text, null: false
      add :wallet_address, :text
      add :wallet_addresses, {:array, :text}, default: []
      add :world_human_id, :text
      add :world_verified_at, :utc_datetime
      add :display_name, :text
      add :avatar, :map

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:human_accounts, [:privy_user_id],
             name: "human_accounts_unique_privy_user_id_index"
           )

    create unique_index(:human_accounts, [:world_human_id],
             name: "human_accounts_unique_world_human_id_index"
           )

    create constraint(:session_authorities, :session_authorities_generation_nonnegative,
             check: """
               generation >= 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:session_authorities, :session_authorities_generation_nonnegative)

    drop_if_exists unique_index(:human_accounts, [:world_human_id],
                     name: "human_accounts_unique_world_human_id_index"
                   )

    drop_if_exists unique_index(:human_accounts, [:privy_user_id],
                     name: "human_accounts_unique_privy_user_id_index"
                   )

    alter table(:human_accounts) do
      remove :updated_at
      remove :created_at
      remove :avatar
      remove :display_name
      remove :world_verified_at
      remove :world_human_id
      remove :wallet_addresses
      remove :wallet_address
      remove :privy_user_id
    end

    drop constraint(:linked_identities, "linked_identities_human_account_id_fkey")

    alter table(:linked_identities) do
      modify :human_account_id, :bigint
    end

    drop constraint(:session_authorities, "session_authorities_human_account_id_fkey")

    alter table(:session_authorities) do
      modify :human_account_id, :bigint
    end

    drop constraint(:x_connections, "x_connections_human_account_id_fkey")

    alter table(:x_connections) do
      modify :human_account_id, :bigint
    end

    drop table(:human_accounts)

    drop_if_exists unique_index(:linked_identities, [:provider, :subject],
                     name: "linked_identities_unique_subject_per_provider_index"
                   )

    drop_if_exists unique_index(:linked_identities, [:provider, :human_account_id],
                     name: "linked_identities_unique_provider_per_account_index"
                   )

    drop table(:linked_identities)

    drop_if_exists unique_index(:session_authorities, [:lineage_digest],
                     name: "session_authorities_unique_lineage_digest_index"
                   )

    drop table(:session_authorities)

    drop_if_exists unique_index(:x_connections, [:human_account_id, :role],
                     name: "x_connections_one_role_per_human_index"
                   )

    drop table(:x_connections)
  end
end
