defmodule Autolaunch.Repo.Migrations.DropStockLaunchDraftStockChainIdDefault do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stock_launch_drafts) do
      modify :stock_chain_id, :bigint, default: nil
    end
  end

  def down do
    alter table(:stock_launch_drafts) do
      modify :stock_chain_id, :bigint, default: 8453
    end
  end
end
