defmodule Autolaunch.Repo.Migrations.DropOperationHashColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:bid_operations, [:bid_transaction_hash],
                     name: "bid_operations_unique_bid_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_operations, [:permit2_approval_transaction_hash],
                     name: "bid_operations_unique_permit2_approval_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_operations, [:token_approval_transaction_hash],
                     name: "bid_operations_unique_token_approval_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_operations, [:usdc_approval_transaction_hash],
                     name: "bid_operations_unique_usdc_approval_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_operations, [:usdc_bid_transaction_hash],
                     name: "bid_operations_unique_usdc_bid_transaction_hash_index"
                   )

    alter table(:bid_operations) do
      remove :token_approval_transaction_hash
      remove :permit2_approval_transaction_hash
      remove :bid_transaction_hash
      remove :usdc_approval_transaction_hash
      remove :usdc_bid_transaction_hash
    end

    drop_if_exists unique_index(:bid_settlement_operations, [:claim_transaction_hash],
                     name: "bid_settlement_operations_unique_claim_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_settlement_operations, [:exit_transaction_hash],
                     name: "bid_settlement_operations_unique_exit_transaction_hash_index"
                   )

    alter table(:bid_settlement_operations) do
      remove :exit_transaction_hash
      remove :claim_transaction_hash
    end

    drop_if_exists unique_index(:launch_operations, [:launch_transaction_hash],
                     name: "launch_operations_unique_launch_hash_index"
                   )

    alter table(:launch_operations) do
      remove :launch_transaction_hash
    end

    drop_if_exists unique_index(:stock_launch_operations, [:launch_transaction_hash],
                     name: "stock_launch_operations_hash_index"
                   )

    alter table(:stock_launch_operations) do
      remove :launch_transaction_hash
    end

    drop_if_exists unique_index(:subject_wallet_operations, [:action_transaction_hash],
                     name: "subject_wallet_operations_unique_action_hash_index"
                   )

    drop_if_exists unique_index(:subject_wallet_operations, [:approval_transaction_hash],
                     name: "subject_wallet_operations_unique_approval_hash_index"
                   )

    alter table(:subject_wallet_operations) do
      remove :approval_transaction_hash
      remove :action_transaction_hash
    end
  end

  def down do
    alter table(:subject_wallet_operations) do
      add :action_transaction_hash, :text
      add :approval_transaction_hash, :text
    end

    create unique_index(:subject_wallet_operations, [:approval_transaction_hash],
             name: "subject_wallet_operations_unique_approval_hash_index"
           )

    create unique_index(:subject_wallet_operations, [:action_transaction_hash],
             name: "subject_wallet_operations_unique_action_hash_index"
           )

    alter table(:stock_launch_operations) do
      add :launch_transaction_hash, :text
    end

    create unique_index(:stock_launch_operations, [:launch_transaction_hash],
             name: "stock_launch_operations_hash_index"
           )

    alter table(:launch_operations) do
      add :launch_transaction_hash, :text
    end

    create unique_index(:launch_operations, [:launch_transaction_hash],
             name: "launch_operations_unique_launch_hash_index"
           )

    alter table(:bid_settlement_operations) do
      add :claim_transaction_hash, :text
      add :exit_transaction_hash, :text
    end

    create unique_index(:bid_settlement_operations, [:exit_transaction_hash],
             name: "bid_settlement_operations_unique_exit_transaction_hash_index"
           )

    create unique_index(:bid_settlement_operations, [:claim_transaction_hash],
             name: "bid_settlement_operations_unique_claim_transaction_hash_index"
           )

    alter table(:bid_operations) do
      add :usdc_bid_transaction_hash, :text
      add :usdc_approval_transaction_hash, :text
      add :bid_transaction_hash, :text
      add :permit2_approval_transaction_hash, :text
      add :token_approval_transaction_hash, :text
    end

    create unique_index(:bid_operations, [:usdc_bid_transaction_hash],
             name: "bid_operations_unique_usdc_bid_transaction_hash_index"
           )

    create unique_index(:bid_operations, [:usdc_approval_transaction_hash],
             name: "bid_operations_unique_usdc_approval_transaction_hash_index"
           )

    create unique_index(:bid_operations, [:token_approval_transaction_hash],
             name: "bid_operations_unique_token_approval_transaction_hash_index"
           )

    create unique_index(:bid_operations, [:permit2_approval_transaction_hash],
             name: "bid_operations_unique_permit2_approval_transaction_hash_index"
           )

    create unique_index(:bid_operations, [:bid_transaction_hash],
             name: "bid_operations_unique_bid_transaction_hash_index"
           )
  end
end
