defmodule Autolaunch.Repo.Migrations.LaunchOrigin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :origin, :text, null: false
    end

    create table(:robinhood_launch_reviews, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :chain_id, :bigint, null: false
      add :signer, :text, null: false
      add :human_account_id, :bigint, null: false
      add :name, :text, null: false
      add :symbol, :text, null: false
      add :stock, :text, null: false
      add :required_stock_raised, :text, null: false
      add :floor_price_q96, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:robinhood_launch_reviews)

    alter table(:auctions) do
      remove :origin
    end
  end
end
