defmodule Autolaunch.Repo.Migrations.HideAuctions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :hidden, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:auctions) do
      remove :hidden
    end
  end
end
