defmodule Autolaunch.Repo.Migrations.RevenuePaymentsReplaceSubjectWallet do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :payments_next_block, :bigint
      add :payments_last_hash, :text
      add :payments_due_at, :utc_datetime_usec
    end

    create index(:auctions, [:payments_due_at, :id], name: "auctions_payments_due_index")

    create table(:revenue_payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :chain_id, :bigint, null: false
      add :receiver, :text, null: false
      add :token, :text, null: false
      add :token_symbol, :text, null: false
      add :gross, :decimal, null: false
      add :net, :decimal, null: false
      add :payer, :text
      add :payment_ref, :text, null: false
      add :transaction_hash, :text, null: false
      add :log_index, :bigint, null: false
      add :block_number, :bigint, null: false
      add :block_hash, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false

      add :auction_id,
          references(:auctions,
            column: :id,
            name: "revenue_payments_auction_id_fkey",
            type: :uuid,
            prefix: "autolaunch_app"
          ),
          null: false
    end

    create unique_index(:revenue_payments, [:chain_id, :transaction_hash, :log_index],
             name: "revenue_payments_chain_log_index"
           )

    create index(:revenue_payments, [:auction_id, :block_number, :log_index])

    alter table(:subjects) do
      remove :splitter_address
      remove :canonical_receiver_address
    end

    # The attempts' reference goes before the table it pointed at.
    alter table(:wallet_attempts) do
      remove :subject_wallet_operation_id
    end

    drop table(:subject_wallet_operations)

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid','usdc_approval','usdc_bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND stock_launch_operation_id IS NOT NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NOT NULL AND step IN ('exit','claim'))
             """
           )

    drop_if_exists index(:wallet_attempts, [:subject_wallet_operation_id, :inserted_at])
  end

  def down do
    # The retired table comes back exactly as it stood before this migration, empty.
    create table(:subject_wallet_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action_id, :text, null: false
      add :subject_id, :text, null: false
      add :kind, :text, null: false
      add :envelope, :map, null: false
      add :signer, :text, null: false
      add :step, :text, null: false
      add :state, :text, null: false, default: "prepared"
      add :result, :map, default: %{}
      add :reason, :text
      add :terminal_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "subject_wallet_operations_human_account_id_fkey",
            type: :bigint,
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:subject_wallet_operations, [:human_account_id, :subject_id],
             name: "subject_wallet_operations_one_open_per_subject_index",
             where: "(terminal_at IS NULL)"
           )

    create unique_index(:subject_wallet_operations, [:action_id],
             name: "subject_wallet_operations_unique_action_id_index"
           )

    alter table(:wallet_attempts) do
      add :subject_wallet_operation_id,
          references(:subject_wallet_operations,
            column: :id,
            name: "wallet_attempts_subject_wallet_operation_id_fkey",
            type: :uuid,
            prefix: "autolaunch_app",
            on_delete: :restrict
          )
    end

    create index(:wallet_attempts, [:subject_wallet_operation_id, :inserted_at])

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid','usdc_approval','usdc_bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','action')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NOT NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NOT NULL AND step IN ('exit','claim'))
             """
           )

    alter table(:subjects) do
      add :canonical_receiver_address, :text
      add :splitter_address, :text
    end

    drop_if_exists index(:revenue_payments, [:auction_id, :block_number, :log_index])

    drop constraint(:revenue_payments, "revenue_payments_auction_id_fkey")

    drop_if_exists unique_index(:revenue_payments, [:chain_id, :transaction_hash, :log_index],
                     name: "revenue_payments_chain_log_index"
                   )

    drop table(:revenue_payments)

    drop_if_exists index(:auctions, [:payments_due_at, :id], name: "auctions_payments_due_index")

    alter table(:auctions) do
      remove :payments_due_at
      remove :payments_last_hash
      remove :payments_next_block
    end
  end
end
