defmodule Autolaunch.Repo.Migrations.DropRobinhoodLaunchReviewFloor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:robinhood_launch_reviews) do
      remove :required_stock_raised
      remove :floor_price_q96
    end
  end

  def down do
    alter table(:robinhood_launch_reviews) do
      add :floor_price_q96, :text, null: false
      add :required_stock_raised, :text, null: false
    end
  end
end
