defmodule Autolaunch.Repo.Migrations.WalletAttempts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:wallet_attempts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :step, :text, null: false
      add :envelope, :map, null: false
      add :legacy, :boolean, null: false, default: false
      add :state, :text, null: false, default: "dispatched"
      add :transaction_hash, :text
      add :result, :map, null: false, default: %{}
      add :evidence, :map, null: false, default: %{}
      add :resolved_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :bid_operation_id,
          references(:bid_operations,
            column: :id,
            name: "wallet_attempts_bid_operation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :launch_operation_id,
          references(:launch_operations,
            column: :id,
            name: "wallet_attempts_launch_operation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :subject_wallet_operation_id,
          references(:subject_wallet_operations,
            column: :id,
            name: "wallet_attempts_subject_wallet_operation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND step IN ('approval','action'))
             """
           )

    # Additive, replay-safe conversion. These are legacy per-step observations,
    # not invented historical presses. Parent rows/hashes are never rewritten.
    execute("""
    INSERT INTO wallet_attempts (id, bid_operation_id, step, envelope, legacy, state, transaction_hash, evidence)
    SELECT md5('legacy:bid_operations:token_approval:' || id::text)::uuid, id, 'token_approval', envelope, true,
           CASE WHEN token_approval_transaction_hash IS NULL THEN 'submission_unknown' ELSE 'submitted' END,
           lower(token_approval_transaction_hash), '{"source":"legacy_operation", "dispatch_time":"unknown"}'::jsonb
    FROM bid_operations
    WHERE token_approval_transaction_hash IS NOT NULL OR (step = 'token_approval' AND state IN ('dispatched','submitted','submission_unknown'))
    ON CONFLICT (id) DO NOTHING
    """)

    execute("""
    INSERT INTO wallet_attempts (id, bid_operation_id, step, envelope, legacy, state, transaction_hash, evidence)
    SELECT md5('legacy:bid_operations:permit2_approval:' || id::text)::uuid, id, 'permit2_approval', envelope, true,
           CASE WHEN permit2_approval_transaction_hash IS NULL THEN 'submission_unknown' ELSE 'submitted' END,
           lower(permit2_approval_transaction_hash), '{"source":"legacy_operation", "dispatch_time":"unknown"}'::jsonb
    FROM bid_operations
    WHERE permit2_approval_transaction_hash IS NOT NULL OR (step = 'permit2_approval' AND state IN ('dispatched','submitted','submission_unknown'))
    ON CONFLICT (id) DO NOTHING
    """)

    execute("""
    INSERT INTO wallet_attempts (id, bid_operation_id, step, envelope, legacy, state, transaction_hash, evidence)
    SELECT md5('legacy:bid_operations:bid:' || id::text)::uuid, id, 'bid', envelope, true,
           CASE WHEN bid_transaction_hash IS NULL THEN 'submission_unknown' ELSE 'submitted' END,
           lower(bid_transaction_hash), '{"source":"legacy_operation", "dispatch_time":"unknown"}'::jsonb
    FROM bid_operations
    WHERE bid_transaction_hash IS NOT NULL OR (step = 'bid' AND state IN ('dispatched','submitted','submission_unknown'))
    ON CONFLICT (id) DO NOTHING
    """)

    execute("""
    INSERT INTO wallet_attempts (id, launch_operation_id, step, envelope, legacy, state, transaction_hash, evidence)
    SELECT md5('legacy:launch_operations:approval:' || id::text)::uuid, id, 'approval', envelope, true,
           CASE WHEN approval_transaction_hash IS NULL THEN 'submission_unknown' ELSE 'submitted' END,
           lower(approval_transaction_hash), '{"source":"legacy_operation", "dispatch_time":"unknown"}'::jsonb
    FROM launch_operations
    WHERE approval_transaction_hash IS NOT NULL OR (step = 'approval' AND state IN ('dispatched','submitted','submission_unknown'))
    ON CONFLICT (id) DO NOTHING
    """)

    execute("""
    INSERT INTO wallet_attempts (id, launch_operation_id, step, envelope, legacy, state, transaction_hash, evidence)
    SELECT md5('legacy:launch_operations:launch:' || id::text)::uuid, id, 'launch', envelope, true,
           CASE WHEN launch_transaction_hash IS NULL THEN 'submission_unknown' ELSE 'submitted' END,
           lower(launch_transaction_hash), '{"source":"legacy_operation", "dispatch_time":"unknown"}'::jsonb
    FROM launch_operations
    WHERE launch_transaction_hash IS NOT NULL OR (step = 'launch' AND state IN ('dispatched','submitted','submission_unknown'))
    ON CONFLICT (id) DO NOTHING
    """)

    execute("""
    INSERT INTO wallet_attempts (id, subject_wallet_operation_id, step, envelope, legacy, state, transaction_hash, evidence)
    SELECT md5('legacy:subject_wallet_operations:approval:' || id::text)::uuid, id, 'approval', envelope, true,
           CASE WHEN approval_transaction_hash IS NULL THEN 'submission_unknown' ELSE 'submitted' END,
           lower(approval_transaction_hash), '{"source":"legacy_operation", "dispatch_time":"unknown"}'::jsonb
    FROM subject_wallet_operations
    WHERE approval_transaction_hash IS NOT NULL OR (step = 'approval' AND state IN ('dispatched','submitted','submission_unknown'))
    ON CONFLICT (id) DO NOTHING
    """)

    execute("""
    INSERT INTO wallet_attempts (id, subject_wallet_operation_id, step, envelope, legacy, state, transaction_hash, evidence)
    SELECT md5('legacy:subject_wallet_operations:action:' || id::text)::uuid, id, 'action', envelope, true,
           CASE WHEN action_transaction_hash IS NULL THEN 'submission_unknown' ELSE 'submitted' END,
           lower(action_transaction_hash), '{"source":"legacy_operation", "dispatch_time":"unknown"}'::jsonb
    FROM subject_wallet_operations
    WHERE action_transaction_hash IS NOT NULL OR (step = 'action' AND state IN ('dispatched','submitted','submission_unknown'))
    ON CONFLICT (id) DO NOTHING
    """)
  end

  def down do
    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    drop constraint(:wallet_attempts, "wallet_attempts_subject_wallet_operation_id_fkey")

    drop constraint(:wallet_attempts, "wallet_attempts_launch_operation_id_fkey")

    drop constraint(:wallet_attempts, "wallet_attempts_bid_operation_id_fkey")

    drop table(:wallet_attempts)
  end
end
