defmodule Autolaunch.Repo.Migrations.BidHistory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Bid activity is derived from chain events. Stored bids lack their bidder,
  # clock block and maximum price, so they are removed and every auction's
  # activity cursor is reset: the activity runner reads each auction again from
  # its start and fills the new columns and the price points.
  def up do
    execute ~s|DELETE FROM "#{prefix()}".bid_activity|

    execute """
    UPDATE "#{prefix()}".auctions SET activity_next_block = NULL, activity_last_hash = NULL,
      bid_volume = NULL, bid_volume_usd = NULL, activity_due_at = now()
    """

    alter table(:bid_activity) do
      add :bidder, :text, null: false
      add :log_index, :bigint, null: false
      add :clock_block, :bigint, null: false
      add :max_price, :decimal, null: false
    end

    create table(:auction_price_points, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :block_number, :bigint, null: false
      add :log_index, :bigint, null: false
      add :clock_block, :bigint, null: false
      add :clearing_price, :decimal, null: false
      add :sold, :decimal, null: false

      add :auction_id,
          references(:auctions,
            column: :id,
            name: "auction_price_points_auction_id_fkey",
            type: :uuid,
            prefix: "autolaunch_app"
          ),
          null: false
    end

    create unique_index(:auction_price_points, [:auction_id, :block_number, :log_index],
             name: "auction_price_points_auction_event_index"
           )
  end

  def down do
    drop constraint(:auction_price_points, "auction_price_points_auction_id_fkey")

    drop_if_exists unique_index(:auction_price_points, [:auction_id, :block_number, :log_index],
                     name: "auction_price_points_auction_event_index"
                   )

    drop table(:auction_price_points)

    alter table(:bid_activity) do
      remove :max_price
      remove :clock_block
      remove :log_index
      remove :bidder
    end
  end
end
