defmodule Autolaunch.Repo.Migrations.AuctionFinishes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:auction_finishes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :launchpad, :text, null: false
      add :chain_id, :bigint, null: false
      add :contract, :text, null: false
      add :launch_id, :bigint, null: false
      add :auction, :text, null: false
      add :migration_block, :bigint, null: false
      add :state, :text, null: false
      add :finish_tx_hash, :text
      add :finish_sent_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:auction_finishes, [:chain_id, :contract, :launch_id],
             name: "auction_finishes_launch_index"
           )
  end

  def down do
    drop_if_exists unique_index(:auction_finishes, [:chain_id, :contract, :launch_id],
                     name: "auction_finishes_launch_index"
                   )

    drop table(:auction_finishes)
  end
end
