defmodule Autolaunch.Repo.Migrations.AuctionCreatorAddress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  # Every stored auction is filled from the wallet that launched it before the
  # column becomes required: a Base launch from its verified launch operation,
  # a Robinhood launch from the review its launcher signed.
  def up do
    alter table(:auctions) do
      add :creator_address, :text
    end

    execute """
    UPDATE "#{prefix()}".auctions a SET creator_address = lower(o.envelope->>'expected_signer')
    FROM "#{prefix()}".launch_operations o
    WHERE lower(o.result->>'auction') = lower(a.auction_address)
    """

    execute """
    UPDATE "#{prefix()}".auctions a SET creator_address = lower(o.envelope->>'expected_signer')
    FROM "#{prefix()}".stock_launch_operations o
    WHERE lower(o.result->>'auction') = lower(a.auction_address)
    """

    execute """
    UPDATE "#{prefix()}".auctions a SET creator_address = lower(r.signer)
    FROM "#{prefix()}".robinhood_launch_reviews r
    WHERE a.creator_address IS NULL
      AND r.chain_id = a.chain_id
      AND r.human_account_id = a.creator_human_account_id
      AND r.name = a.title
      AND lower(r.stock) = lower(a.quote_token_address)
      AND r.required_stock_raised = a.required_currency_raised
    """

    alter table(:auctions) do
      modify :creator_address, :text, null: false
    end
  end

  def down do
    alter table(:auctions) do
      remove :creator_address
    end
  end
end
