defmodule Autolaunch.Repo.Migrations.MemestockCreatePage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :telegram, :text
    end

    alter table(:robinhood_launch_reviews) do
      add :telegram, :text
    end

    drop_if_exists unique_index(:stock_launch_drafts, [:human_account_id, :chain],
                     name: "stock_launch_drafts_one_stocks_draft_per_human_and_chain_index"
                   )

    alter table(:stock_launch_drafts) do
      add :telegram, :text
    end

    # One draft per account from here on. An account's most recently saved
    # draft is kept; any image versions or launches of its others move onto
    # it, so no served image address or launch record is lost, and the others
    # are removed.
    execute """
    CREATE TEMP TABLE merged_stock_drafts ON COMMIT DROP AS
    SELECT d.id, k.id AS kept_id
    FROM "#{prefix()}".stock_launch_drafts d
    JOIN LATERAL (
      SELECT id FROM "#{prefix()}".stock_launch_drafts
      WHERE human_account_id = d.human_account_id
      ORDER BY updated_at DESC, id
      LIMIT 1
    ) k ON k.id <> d.id
    """

    execute """
    UPDATE "#{prefix()}".stock_launch_draft_images i SET stock_launch_draft_id = m.kept_id
    FROM merged_stock_drafts m WHERE i.stock_launch_draft_id = m.id
    """

    execute """
    UPDATE "#{prefix()}".stock_launch_operations o SET launch_draft_id = m.kept_id
    FROM merged_stock_drafts m WHERE o.launch_draft_id = m.id
    """

    execute """
    DELETE FROM "#{prefix()}".stock_launch_drafts d
    USING merged_stock_drafts m WHERE d.id = m.id
    """

    create unique_index(:stock_launch_drafts, [:human_account_id],
             name: "stock_launch_drafts_one_stocks_draft_per_human_index"
           )

    alter table(:stock_launch_drafts) do
      modify :required_raise, :text, default: "0.00001"
      modify :floor_price, :text, default: "0.00000001"
    end

    execute """
    UPDATE "#{prefix()}".stock_launch_drafts
    SET required_raise = coalesce(required_raise, '0.00001'),
        floor_price = coalesce(floor_price, '0.00000001')
    WHERE required_raise IS NULL OR floor_price IS NULL
    """
  end

  def down do
    alter table(:stock_launch_drafts) do
      modify :floor_price, :text, default: nil
      modify :required_raise, :text, default: nil
    end

    drop_if_exists unique_index(:stock_launch_drafts, [:human_account_id],
                     name: "stock_launch_drafts_one_stocks_draft_per_human_index"
                   )

    alter table(:stock_launch_drafts) do
      remove :telegram
    end

    create unique_index(:stock_launch_drafts, [:human_account_id, :chain],
             name: "stock_launch_drafts_one_stocks_draft_per_human_and_chain_index"
           )

    alter table(:robinhood_launch_reviews) do
      remove :telegram
    end

    alter table(:auctions) do
      remove :telegram
    end
  end
end
