defmodule Autolaunch.Repo.Migrations.LaunchDiscoveries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:launch_discoveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :launchpad, :text, null: false
      add :chain_id, :bigint, null: false
      add :contract, :text, null: false
      add :launch_id, :bigint, null: false
      add :launcher, :text, null: false
      add :auction, :text, null: false
      add :transaction_hash, :text, null: false
      add :state, :text, null: false, default: "pending"
      add :creator_human_account_id, :bigint
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:launch_discoveries, [:chain_id, :contract, :launch_id],
             name: "launch_discoveries_launch_index"
           )
  end

  def down do
    drop_if_exists unique_index(:launch_discoveries, [:chain_id, :contract, :launch_id],
                     name: "launch_discoveries_launch_index"
                   )

    drop table(:launch_discoveries)
  end
end
