defmodule Autolaunch.Repo.Migrations.RobinhoodLaunchFacts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :token_address, :text
      add :launch_id, :bigint
      add :start_block, :bigint
      add :end_block, :bigint
    end
  end

  def down do
    alter table(:auctions) do
      remove :end_block
      remove :start_block
      remove :launch_id
      remove :token_address
    end
  end
end
