defmodule Autolaunch.Repo.Migrations.StocksLaunch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :kind, :text, null: false, default: "agent"
    end

    alter table(:bid_operations) do
      add :usdc_approval_transaction_hash, :text
      add :usdc_bid_transaction_hash, :text
    end

    create unique_index(:bid_operations, [:usdc_approval_transaction_hash],
             name: "bid_operations_unique_usdc_approval_transaction_hash_index"
           )

    create unique_index(:bid_operations, [:usdc_bid_transaction_hash],
             name: "bid_operations_unique_usdc_bid_transaction_hash_index"
           )

    create table(:stock_launch_drafts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false, default: ""
      add :symbol, :text, null: false, default: ""
      add :description, :text
      add :website, :text
      add :image, :text
      add :stock_address, :text
      add :stock_chain_id, :bigint, null: false, default: 8453
      add :start_at, :utc_datetime
      add :start_timezone, :text
      add :minimum_raise, :text
      add :floor_price, :text
      add :subject_enabled, :boolean, null: false, default: false
      add :subject_splitter, :text
      add :fee_administrator, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "stock_launch_drafts_human_account_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:stock_launch_drafts, [:human_account_id],
             name: "stock_launch_drafts_one_stocks_draft_per_human_index"
           )

    create table(:stock_launch_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action_id, :text, null: false
      add :envelope, :map, null: false
      add :signer, :text, null: false
      add :step, :text, null: false, default: "launch"
      add :state, :text, null: false, default: "prepared"
      add :launch_transaction_hash, :text
      add :result, :map, default: %{}
      add :reason, :text
      add :terminal_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "stock_launch_operations_human_account_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:stock_launch_operations, [:action_id],
             name: "stock_launch_operations_action_id_index"
           )

    create unique_index(:stock_launch_operations, [:launch_transaction_hash],
             name: "stock_launch_operations_hash_index"
           )

    alter table(:stock_launch_operations) do
      add :launch_draft_id,
          references(:stock_launch_drafts,
            column: :id,
            name: "stock_launch_operations_launch_draft_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:stock_launch_operations, [:human_account_id],
             name: "stock_launch_operations_one_open_index",
             where: "(terminal_at IS NULL)"
           )

    alter table(:wallet_attempts) do
      add :stock_launch_operation_id,
          references(:stock_launch_operations,
            column: :id,
            name: "wallet_attempts_stock_launch_operation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid','usdc_approval','usdc_bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND stock_launch_operation_id IS NULL AND step IN ('approval','action')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NOT NULL AND step = 'launch')
             """
           )

    create index(:wallet_attempts, [:stock_launch_operation_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:wallet_attempts, [:stock_launch_operation_id, :inserted_at])

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND step IN ('approval','action'))
             """
           )

    drop constraint(:wallet_attempts, "wallet_attempts_stock_launch_operation_id_fkey")

    alter table(:wallet_attempts) do
      remove :stock_launch_operation_id
    end

    drop constraint(:stock_launch_operations, "stock_launch_operations_launch_draft_id_fkey")

    drop constraint(:stock_launch_operations, "stock_launch_operations_human_account_id_fkey")

    drop_if_exists unique_index(:stock_launch_operations, [:human_account_id],
                     name: "stock_launch_operations_one_open_index"
                   )

    alter table(:stock_launch_operations) do
      remove :launch_draft_id
    end

    drop_if_exists unique_index(:stock_launch_operations, [:launch_transaction_hash],
                     name: "stock_launch_operations_hash_index"
                   )

    drop_if_exists unique_index(:stock_launch_operations, [:action_id],
                     name: "stock_launch_operations_action_id_index"
                   )

    drop table(:stock_launch_operations)

    drop constraint(:stock_launch_drafts, "stock_launch_drafts_human_account_id_fkey")

    drop_if_exists unique_index(:stock_launch_drafts, [:human_account_id],
                     name: "stock_launch_drafts_one_stocks_draft_per_human_index"
                   )

    drop table(:stock_launch_drafts)

    drop_if_exists unique_index(:bid_operations, [:usdc_bid_transaction_hash],
                     name: "bid_operations_unique_usdc_bid_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_operations, [:usdc_approval_transaction_hash],
                     name: "bid_operations_unique_usdc_approval_transaction_hash_index"
                   )

    alter table(:bid_operations) do
      remove :usdc_bid_transaction_hash
      remove :usdc_approval_transaction_hash
    end

    alter table(:auctions) do
      remove :kind
    end
  end
end
