defmodule Autolaunch.Repo.Migrations.DropMemestakeDraftPriceInputs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stock_launch_drafts) do
      remove :required_raise
      remove :floor_price
    end
  end

  def down do
    alter table(:stock_launch_drafts) do
      add :floor_price, :text, default: "0.00000001"
      add :required_raise, :text, default: "0.00001"
    end
  end
end
