defmodule Autolaunch.Repo.Migrations.LaunchTerms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:launch_operations, [:approval_transaction_hash],
                     name: "launch_operations_unique_launch_approval_hash_index"
                   )

    alter table(:launch_operations) do
      remove :approval_transaction_hash
    end

    alter table(:stock_launch_drafts) do
      add :required_raise, :text
      remove :start_at
      remove :start_timezone
    end

    drop_if_exists unique_index(:stock_launch_operations, [:approval_transaction_hash],
                     name: "stock_launch_operations_approval_hash_index"
                   )

    alter table(:stock_launch_operations) do
      remove :approval_transaction_hash
    end
  end

  def down do
    alter table(:stock_launch_operations) do
      add :approval_transaction_hash, :text
    end

    create unique_index(:stock_launch_operations, [:approval_transaction_hash],
             name: "stock_launch_operations_approval_hash_index"
           )

    alter table(:stock_launch_drafts) do
      add :start_timezone, :text
      add :start_at, :utc_datetime
      remove :required_raise
    end

    alter table(:launch_operations) do
      add :approval_transaction_hash, :text
    end

    create unique_index(:launch_operations, [:approval_transaction_hash],
             name: "launch_operations_unique_launch_approval_hash_index"
           )
  end
end
