defmodule Autolaunch.Repo.Migrations.TokenTrades do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:token_trades, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :transaction_hash, :text, null: false
      add :block_hash, :text, null: false
      add :block_number, :bigint, null: false
      add :log_index, :bigint, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :side, :text, null: false
      add :currency_amount, :decimal, null: false
      add :currency_symbol, :text, null: false
      add :token_amount, :decimal, null: false

      add :token_id,
          references(:tokens,
            column: :id,
            name: "token_trades_token_id_fkey",
            type: :uuid,
            prefix: "autolaunch_app"
          ), null: false
    end

    create unique_index(:token_trades, [:token_id, :transaction_hash, :log_index],
             name: "token_trades_pool_log_index"
           )

    create index(:token_trades, [:token_id, :block_number])

    create index(:token_trades, ["occurred_at DESC", "id"], name: "token_trades_recent_index")

    alter table(:tokens) do
      add :trades_next_block, :bigint
      add :trades_last_hash, :text
      add :trades_due_at, :utc_datetime_usec
    end

    create index(:tokens, [:trades_due_at, :id], name: "tokens_trades_due_index")
  end

  def down do
    drop_if_exists index(:tokens, [:trades_due_at, :id], name: "tokens_trades_due_index")

    alter table(:tokens) do
      remove :trades_due_at
      remove :trades_last_hash
      remove :trades_next_block
    end

    drop_if_exists index(:token_trades, ["occurred_at DESC", "id"],
                     name: "token_trades_recent_index"
                   )

    drop_if_exists index(:token_trades, [:token_id, :block_number])

    drop constraint(:token_trades, "token_trades_token_id_fkey")

    drop_if_exists unique_index(:token_trades, [:token_id, :transaction_hash, :log_index],
                     name: "token_trades_pool_log_index"
                   )

    drop table(:token_trades)
  end
end
