defmodule Autolaunch.Repo.Migrations.FaucetGrants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:faucet_grants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :wallet, :text, null: false
      add :asset, :text, null: false
      add :granted_at, :utc_datetime_usec, null: false
    end

    create unique_index(:faucet_grants, [:wallet, :asset],
             name: "faucet_grants_wallet_asset_index"
           )
  end

  def down do
    drop_if_exists unique_index(:faucet_grants, [:wallet, :asset],
                     name: "faucet_grants_wallet_asset_index"
                   )

    drop table(:faucet_grants)
  end
end
