defmodule Autolaunch.Repo.Migrations.DropPagePublicIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:auctions, ["opened_at DESC NULLS LAST", "inserted_at DESC", "id"],
                     name: "auctions_public_newest_index"
                   )

    drop_if_exists index(:auctions, [:opened_at, :inserted_at, :id],
                     name: "auctions_public_oldest_index"
                   )
  end

  def down do
    create index(:auctions, [:opened_at, :inserted_at, :id], name: "auctions_public_oldest_index")

    create index(:auctions, ["opened_at DESC NULLS LAST", "inserted_at DESC", "id"],
             name: "auctions_public_newest_index"
           )
  end
end
