defmodule Autolaunch.Repo.Migrations.AuctionActivity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :activity_next_block, :bigint
      add :activity_last_hash, :text
      add :activity_due_at, :utc_datetime_usec
      add :bid_volume, :decimal
      add :bid_volume_usd, :decimal
      add :estimated_end_at, :utc_datetime_usec
    end

    create index(:auctions, [:activity_due_at, :id], name: "auctions_activity_due_index")

    create index(:auctions, [:estimated_end_at, :id], name: "auctions_ending_index")

    create index(:auctions, ["bid_volume_usd DESC NULLS LAST", "id"],
             name: "auctions_bid_volume_index"
           )

    create table(:bid_activity, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bid_id, :text, null: false
      add :transaction_hash, :text, null: false
      add :block_hash, :text, null: false
      add :block_number, :bigint, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :amount, :decimal, null: false
      add :display_amount, :decimal, null: false
      add :display_symbol, :text, null: false

      add :auction_id,
          references(:auctions,
            column: :id,
            name: "bid_activity_auction_id_fkey",
            type: :uuid,
            prefix: "autolaunch_app"
          ),
          null: false
    end

    create unique_index(:bid_activity, [:auction_id, :bid_id],
             name: "bid_activity_auction_bid_index"
           )

    create index(:bid_activity, [:auction_id, :block_number])

    create index(:bid_activity, ["occurred_at DESC", "id"], name: "bid_activity_recent_index")
  end

  def down do
    drop_if_exists index(:bid_activity, ["occurred_at DESC", "id"],
                     name: "bid_activity_recent_index"
                   )

    drop_if_exists index(:bid_activity, [:auction_id, :block_number])

    drop constraint(:bid_activity, "bid_activity_auction_id_fkey")

    drop_if_exists unique_index(:bid_activity, [:auction_id, :bid_id],
                     name: "bid_activity_auction_bid_index"
                   )

    drop table(:bid_activity)

    drop_if_exists index(:auctions, ["bid_volume_usd DESC NULLS LAST", "id"],
                     name: "auctions_bid_volume_index"
                   )

    drop_if_exists index(:auctions, [:estimated_end_at, :id], name: "auctions_ending_index")

    drop_if_exists index(:auctions, [:activity_due_at, :id], name: "auctions_activity_due_index")

    alter table(:auctions) do
      remove :estimated_end_at
      remove :bid_volume_usd
      remove :bid_volume
      remove :activity_due_at
      remove :activity_last_hash
      remove :activity_next_block
    end
  end
end
