defmodule Autolaunch.Repo.Migrations.AuctionEndedState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :minimum_reached, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:auctions) do
      remove :minimum_reached
    end
  end
end
