defmodule Autolaunch.Repo.Migrations.AddLaunchOperationChain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:launch_operations) do
      add :chain, :text, null: false, default: "base"
    end
  end

  def down do
    alter table(:launch_operations) do
      remove :chain
    end
  end
end
