defmodule Autolaunch.Repo.Migrations.AllowManyOpenSettlementAndLaunchReviews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:launch_operations, [:human_account_id],
                     name: "launch_operations_one_open_per_account_index"
                   )

    drop_if_exists unique_index(:stock_launch_operations, [:human_account_id],
                     name: "stock_launch_operations_one_open_index"
                   )

    drop_if_exists unique_index(:bid_settlement_operations, [:bid_position_id],
                     name: "bid_settlement_operations_one_open_per_position_index"
                   )
  end

  def down do
    create unique_index(:bid_settlement_operations, [:bid_position_id],
             name: "bid_settlement_operations_one_open_per_position_index",
             where: "(terminal_at IS NULL)"
           )

    create unique_index(:stock_launch_operations, [:human_account_id],
             name: "stock_launch_operations_one_open_index",
             where: "(terminal_at IS NULL)"
           )

    create unique_index(:launch_operations, [:human_account_id],
             name: "launch_operations_one_open_per_account_index",
             where: "(terminal_at IS NULL)"
           )
  end
end
