defmodule Autolaunch.Repo.Migrations.AllowManyOpenBidReviews do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:bid_operations, [:human_account_id],
                     name: "bid_operations_one_open_per_account_index"
                   )
  end

  def down do
    create unique_index(:bid_operations, [:human_account_id],
             name: "bid_operations_one_open_per_account_index",
             where: "(terminal_at IS NULL)"
           )
  end
end
