defmodule Autolaunch.Repo.Migrations.AuctionMarketFigures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :currency_raised, :decimal
      add :floor_price, :text
      add :token_supply, :decimal
    end
  end

  def down do
    alter table(:auctions) do
      remove :token_supply
      remove :floor_price
      remove :currency_raised
    end
  end
end
