defmodule Autolaunch.Repo.Migrations.BidSettlement do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:bid_settlement_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action_id, :text, null: false
      add :envelope, :map, null: false
      add :signer, :text, null: false
      add :step, :text, null: false
      add :state, :text, null: false, default: "prepared"
      add :exit_transaction_hash, :text
      add :claim_transaction_hash, :text
      add :result, :map, null: false, default: %{}
      add :reason, :text
      add :terminal_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "bid_settlement_operations_human_account_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:bid_settlement_operations, [:action_id],
             name: "bid_settlement_operations_unique_action_id_index"
           )

    create unique_index(:bid_settlement_operations, [:claim_transaction_hash],
             name: "bid_settlement_operations_unique_claim_transaction_hash_index"
           )

    create unique_index(:bid_settlement_operations, [:exit_transaction_hash],
             name: "bid_settlement_operations_unique_exit_transaction_hash_index"
           )

    alter table(:bid_settlement_operations) do
      add :bid_position_id,
          references(:bids,
            column: :id,
            name: "bid_settlement_operations_bid_position_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:bid_settlement_operations, [:bid_position_id],
             name: "bid_settlement_operations_one_open_per_position_index",
             where: "(terminal_at IS NULL)"
           )

    alter table(:bids) do
      add :currency_refunded, :text
      add :tokens_filled, :text
      add :tokens_claimed, :text
    end

    alter table(:wallet_attempts) do
      add :bid_settlement_operation_id,
          references(:bid_settlement_operations,
            column: :id,
            name: "wallet_attempts_bid_settlement_operation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid','usdc_approval','usdc_bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','action')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NOT NULL AND bid_settlement_operation_id IS NULL AND step = 'launch') OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NOT NULL AND step IN ('exit','claim'))
             """
           )

    create index(:wallet_attempts, [:bid_settlement_operation_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:wallet_attempts, [:bid_settlement_operation_id, :inserted_at])

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid','usdc_approval','usdc_bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND stock_launch_operation_id IS NULL AND step IN ('approval','action')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NOT NULL AND step = 'launch')
             """
           )

    drop constraint(:wallet_attempts, "wallet_attempts_bid_settlement_operation_id_fkey")

    alter table(:wallet_attempts) do
      remove :bid_settlement_operation_id
    end

    alter table(:bids) do
      remove :tokens_claimed
      remove :tokens_filled
      remove :currency_refunded
    end

    drop constraint(:bid_settlement_operations, "bid_settlement_operations_bid_position_id_fkey")

    drop constraint(:bid_settlement_operations, "bid_settlement_operations_human_account_id_fkey")

    drop_if_exists unique_index(:bid_settlement_operations, [:bid_position_id],
                     name: "bid_settlement_operations_one_open_per_position_index"
                   )

    alter table(:bid_settlement_operations) do
      remove :bid_position_id
    end

    drop_if_exists unique_index(:bid_settlement_operations, [:exit_transaction_hash],
                     name: "bid_settlement_operations_unique_exit_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_settlement_operations, [:claim_transaction_hash],
                     name: "bid_settlement_operations_unique_claim_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_settlement_operations, [:action_id],
                     name: "bid_settlement_operations_unique_action_id_index"
                   )

    drop table(:bid_settlement_operations)
  end
end
