defmodule Autolaunch.Repo.Migrations.StocksLaunchDraftImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stock_launch_draft_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :digest, :text, null: false
      add :content_type, :text, null: false
      add :byte_size, :bigint, null: false
      add :bytes, :binary, null: false
      add :original_filename, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "stock_launch_draft_images_human_account_id_fkey",
            type: :bigint,
            on_delete: :restrict
          ), null: false

      add :stock_launch_draft_id,
          references(:stock_launch_drafts,
            column: :id,
            name: "stock_launch_draft_images_stock_launch_draft_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ), null: false
    end

    create unique_index(:stock_launch_draft_images, [:stock_launch_draft_id, :digest],
             name: "stock_launch_draft_images_one_version_per_stock_draft_index"
           )

    alter table(:stock_launch_drafts) do
      add :stock_launch_draft_image_id,
          references(:stock_launch_draft_images,
            column: :id,
            name: "stock_launch_drafts_stock_launch_draft_image_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )
    end

    create index(:stock_launch_drafts, [:stock_launch_draft_image_id])
  end

  def down do
    drop_if_exists index(:stock_launch_drafts, [:stock_launch_draft_image_id])

    drop constraint(:stock_launch_drafts, "stock_launch_drafts_stock_launch_draft_image_id_fkey")

    alter table(:stock_launch_drafts) do
      remove :stock_launch_draft_image_id
    end

    drop constraint(
           :stock_launch_draft_images,
           "stock_launch_draft_images_stock_launch_draft_id_fkey"
         )

    drop constraint(:stock_launch_draft_images, "stock_launch_draft_images_human_account_id_fkey")

    drop_if_exists unique_index(:stock_launch_draft_images, [:stock_launch_draft_id, :digest],
                     name: "stock_launch_draft_images_one_version_per_stock_draft_index"
                   )

    drop table(:stock_launch_draft_images)
  end
end
