defmodule Autolaunch.Repo.Migrations.AuctionFinishTransactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:auction_finish_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :chain_id, :bigint, null: false
      add :signer, :text, null: false
      add :nonce, :bigint, null: false
      add :transaction_hash, :text, null: false
      add :raw_transaction, :text, null: false
      add :state, :text, null: false, default: "signed"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :auction_finish_id,
          references(:auction_finishes,
            column: :id,
            name: "auction_finish_transactions_auction_finish_id_fkey",
            type: :uuid,
            prefix: "autolaunch_app",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:auction_finish_transactions, [:chain_id, :signer, :nonce],
             name: "auction_finish_transactions_nonce_index"
           )

    create unique_index(:auction_finish_transactions, [:auction_finish_id],
             name: "auction_finish_transactions_unsettled_index",
             where: "(state = 'signed')"
           )

    alter table(:auction_finishes) do
      remove :finish_tx_hash
      remove :finish_sent_at
    end
  end

  def down do
    alter table(:auction_finishes) do
      add :finish_sent_at, :utc_datetime_usec
      add :finish_tx_hash, :text
    end

    drop constraint(
           :auction_finish_transactions,
           "auction_finish_transactions_auction_finish_id_fkey"
         )

    drop_if_exists unique_index(:auction_finish_transactions, [:auction_finish_id],
                     name: "auction_finish_transactions_unsettled_index"
                   )

    drop_if_exists unique_index(:auction_finish_transactions, [:chain_id, :signer, :nonce],
                     name: "auction_finish_transactions_nonce_index"
                   )

    drop table(:auction_finish_transactions)
  end
end
