defmodule Autolaunch.Repo.Migrations.StocksLaunchFee do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stock_launch_operations) do
      add :approval_transaction_hash, :text
    end

    create unique_index(:stock_launch_operations, [:approval_transaction_hash],
             name: "stock_launch_operations_approval_hash_index"
           )

    alter table(:stock_launch_operations) do
      modify :step, :text, default: nil
    end
  end

  def down do
    alter table(:stock_launch_operations) do
      modify :step, :text, default: "launch"
    end

    drop_if_exists unique_index(:stock_launch_operations, [:approval_transaction_hash],
                     name: "stock_launch_operations_approval_hash_index"
                   )

    alter table(:stock_launch_operations) do
      remove :approval_transaction_hash
    end
  end
end
