defmodule Autolaunch.Repo.Migrations.WalletAttemptDropLegacy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:wallet_attempts) do
      remove :legacy
    end
  end

  def down do
    alter table(:wallet_attempts) do
      add :legacy, :boolean, null: false, default: false
    end
  end
end
