defmodule Autolaunch.Repo.Migrations.StocksFeeAdmin do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stock_fee_admin_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action_id, :text, null: false
      add :kind, :text, null: false
      add :envelope, :map, null: false
      add :signer, :text, null: false
      add :step, :text, null: false, default: "action"
      add :state, :text, null: false, default: "prepared"
      add :action_transaction_hash, :text
      add :result, :map, default: %{}
      add :reason, :text
      add :terminal_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "stock_fee_admin_operations_human_account_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :restrict
          ), null: false
    end

    create unique_index(:stock_fee_admin_operations, [:action_transaction_hash],
             name: "stock_fee_admin_operations_hash_index"
           )

    create unique_index(:stock_fee_admin_operations, [:action_id],
             name: "stock_fee_admin_operations_action_id_index"
           )

    alter table(:stock_fee_admin_operations) do
      add :auction_id,
          references(:auctions,
            column: :id,
            name: "stock_fee_admin_operations_auction_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false
    end

    create unique_index(:stock_fee_admin_operations, [:human_account_id, :auction_id],
             name: "stock_fee_admin_operations_one_open_index",
             where: "(terminal_at IS NULL)"
           )

    alter table(:wallet_attempts) do
      add :stock_fee_admin_operation_id,
          references(:stock_fee_admin_operations,
            column: :id,
            name: "wallet_attempts_stock_fee_admin_operation_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND stock_fee_admin_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid','usdc_approval','usdc_bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND stock_fee_admin_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND stock_launch_operation_id IS NULL AND stock_fee_admin_operation_id IS NULL AND step IN ('approval','action')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NOT NULL AND stock_fee_admin_operation_id IS NULL AND step = 'launch') OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND stock_fee_admin_operation_id IS NOT NULL AND step = 'action')
             """
           )

    create index(:wallet_attempts, [:stock_fee_admin_operation_id, :inserted_at])
  end

  def down do
    drop_if_exists index(:wallet_attempts, [:stock_fee_admin_operation_id, :inserted_at])

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid','usdc_approval','usdc_bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND stock_launch_operation_id IS NULL AND step IN ('approval','action')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NOT NULL AND step = 'launch')
             """
           )

    drop constraint(:wallet_attempts, "wallet_attempts_stock_fee_admin_operation_id_fkey")

    alter table(:wallet_attempts) do
      remove :stock_fee_admin_operation_id
    end

    drop constraint(:stock_fee_admin_operations, "stock_fee_admin_operations_auction_id_fkey")

    drop constraint(
           :stock_fee_admin_operations,
           "stock_fee_admin_operations_human_account_id_fkey"
         )

    drop_if_exists unique_index(:stock_fee_admin_operations, [:human_account_id, :auction_id],
                     name: "stock_fee_admin_operations_one_open_index"
                   )

    alter table(:stock_fee_admin_operations) do
      remove :auction_id
    end

    drop_if_exists unique_index(:stock_fee_admin_operations, [:action_id],
                     name: "stock_fee_admin_operations_action_id_index"
                   )

    drop_if_exists unique_index(:stock_fee_admin_operations, [:action_transaction_hash],
                     name: "stock_fee_admin_operations_hash_index"
                   )

    drop table(:stock_fee_admin_operations)
  end
end
