defmodule Autolaunch.Repo.Migrations.MemestakeCutover do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stock_launch_drafts) do
      remove :subject_enabled
      remove :subject_splitter
      remove :fee_administrator
    end

    # The attempts' reference goes before the table it pointed at.
    alter table(:wallet_attempts) do
      remove :stock_fee_admin_operation_id
    end

    drop table(:stock_fee_admin_operations)

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid','usdc_approval','usdc_bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','action')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NOT NULL AND bid_settlement_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NOT NULL AND step IN ('exit','claim'))
             """
           )

    drop_if_exists index(:wallet_attempts, [:stock_fee_admin_operation_id, :inserted_at])
  end

  def down do
    # The retired table comes back exactly as 20260909200435 created it, empty.
    create table(:stock_fee_admin_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action_id, :text, null: false
      add :kind, :text, null: false
      add :envelope, :map, null: false
      add :signer, :text, null: false
      add :step, :text, null: false, default: "action"
      add :state, :text, null: false, default: "prepared"
      add :action_transaction_hash, :text
      add :result, :map, default: %{}
      add :reason, :text
      add :terminal_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "stock_fee_admin_operations_human_account_id_fkey",
            type: :bigint,
            on_delete: :restrict
          ),
          null: false

      add :auction_id,
          references(:auctions,
            column: :id,
            name: "stock_fee_admin_operations_auction_id_fkey",
            type: :uuid,
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:stock_fee_admin_operations, [:action_transaction_hash],
             name: "stock_fee_admin_operations_hash_index"
           )

    create unique_index(:stock_fee_admin_operations, [:action_id],
             name: "stock_fee_admin_operations_action_id_index"
           )

    create unique_index(:stock_fee_admin_operations, [:human_account_id, :auction_id],
             name: "stock_fee_admin_operations_one_open_index",
             where: "(terminal_at IS NULL)"
           )

    alter table(:wallet_attempts) do
      add :stock_fee_admin_operation_id,
          references(:stock_fee_admin_operations,
            column: :id,
            name: "wallet_attempts_stock_fee_admin_operation_id_fkey",
            type: :uuid,
            on_delete: :restrict
          )
    end

    create index(:wallet_attempts, [:stock_fee_admin_operation_id, :inserted_at])

    drop_if_exists constraint(:wallet_attempts, :wallet_attempt_parent_step)

    create constraint(:wallet_attempts, :wallet_attempt_parent_step,
             check: """
               (bid_operation_id IS NOT NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND stock_fee_admin_operation_id IS NULL AND step IN ('token_approval','permit2_approval','bid','usdc_approval','usdc_bid')) OR (bid_operation_id IS NULL AND launch_operation_id IS NOT NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND stock_fee_admin_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NOT NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND stock_fee_admin_operation_id IS NULL AND step IN ('approval','action')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NOT NULL AND bid_settlement_operation_id IS NULL AND stock_fee_admin_operation_id IS NULL AND step IN ('approval','launch')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NOT NULL AND stock_fee_admin_operation_id IS NULL AND step IN ('exit','claim')) OR (bid_operation_id IS NULL AND launch_operation_id IS NULL AND subject_wallet_operation_id IS NULL AND stock_launch_operation_id IS NULL AND bid_settlement_operation_id IS NULL AND stock_fee_admin_operation_id IS NOT NULL AND step = 'action')
             """
           )

    alter table(:stock_launch_drafts) do
      add :fee_administrator, :text
      add :subject_splitter, :text
      add :subject_enabled, :boolean, null: false, default: false
    end
  end
end
