defmodule Autolaunch.Repo.Migrations.AddLaunchDraftChain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:launch_drafts, [:human_account_id],
                     name: "launch_drafts_one_account_owned_draft_per_human_index"
                   )

    alter table(:launch_drafts) do
      add :chain, :text, null: false, default: "base"
    end

    create unique_index(:launch_drafts, [:human_account_id, :chain],
             name: "launch_drafts_one_account_owned_draft_per_human_and_chain_index"
           )

    drop_if_exists unique_index(:stock_launch_drafts, [:human_account_id],
                     name: "stock_launch_drafts_one_stocks_draft_per_human_index"
                   )

    alter table(:stock_launch_drafts) do
      add :chain, :text, null: false, default: "base"
    end

    create unique_index(:stock_launch_drafts, [:human_account_id, :chain],
             name: "stock_launch_drafts_one_stocks_draft_per_human_and_chain_index"
           )
  end

  def down do
    drop_if_exists unique_index(:stock_launch_drafts, [:human_account_id, :chain],
                     name: "stock_launch_drafts_one_stocks_draft_per_human_and_chain_index"
                   )

    alter table(:stock_launch_drafts) do
      remove :chain
    end

    create unique_index(:stock_launch_drafts, [:human_account_id],
             name: "stock_launch_drafts_one_stocks_draft_per_human_index"
           )

    drop_if_exists unique_index(:launch_drafts, [:human_account_id, :chain],
                     name: "launch_drafts_one_account_owned_draft_per_human_and_chain_index"
                   )

    alter table(:launch_drafts) do
      remove :chain
    end

    create unique_index(:launch_drafts, [:human_account_id],
             name: "launch_drafts_one_account_owned_draft_per_human_index"
           )
  end
end
