defmodule Autolaunch.Repo.Migrations.ReplaceableLaunchImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:launch_draft_images, [:launch_draft_id],
                     name: "launch_draft_images_one_image_per_draft_index"
                   )

    create unique_index(:launch_draft_images, [:launch_draft_id, :digest],
             name: "launch_draft_images_one_version_per_draft_index"
           )
  end

  def down do
    drop_if_exists unique_index(:launch_draft_images, [:launch_draft_id, :digest],
                     name: "launch_draft_images_one_version_per_draft_index"
                   )

    create unique_index(:launch_draft_images, [:launch_draft_id],
             name: "launch_draft_images_one_image_per_draft_index"
           )
  end
end
