defmodule Autolaunch.Repo.Migrations.AuctionRequiredRaise do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :required_currency_raised, :text, null: false
    end
  end

  def down do
    alter table(:auctions) do
      remove :required_currency_raised
    end
  end
end
