defmodule Autolaunch.Repo.Migrations.WalletAttemptIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:wallet_attempts, [:bid_operation_id, :inserted_at])

    create index(:wallet_attempts, [:launch_operation_id, :inserted_at])

    create index(:wallet_attempts, [:subject_wallet_operation_id, :inserted_at])

    create index(:wallet_attempts, [:transaction_hash, :step, :state])
  end

  def down do
    drop_if_exists index(:wallet_attempts, [:transaction_hash, :step, :state])

    drop_if_exists index(:wallet_attempts, [:subject_wallet_operation_id, :inserted_at])

    drop_if_exists index(:wallet_attempts, [:launch_operation_id, :inserted_at])

    drop_if_exists index(:wallet_attempts, [:bid_operation_id, :inserted_at])
  end
end
