defmodule Autolaunch.Repo.Migrations.AddLaunchLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      add :discord, :text
      add :links, {:array, :text}, null: false, default: []
    end

    alter table(:launch_drafts) do
      add :telegram, :text
      add :discord, :text
      add :other_link_1, :text
      add :other_link_2, :text
      add :other_link_3, :text
    end

    alter table(:robinhood_launch_reviews) do
      add :discord, :text
      add :links, {:array, :text}, null: false, default: []
    end

    alter table(:stock_launch_drafts) do
      add :discord, :text
      add :other_link_1, :text
      add :other_link_2, :text
      add :other_link_3, :text
    end
  end

  def down do
    alter table(:stock_launch_drafts) do
      remove :other_link_3
      remove :other_link_2
      remove :other_link_1
      remove :discord
    end

    alter table(:robinhood_launch_reviews) do
      remove :links
      remove :discord
    end

    alter table(:launch_drafts) do
      remove :other_link_3
      remove :other_link_2
      remove :other_link_1
      remove :discord
      remove :telegram
    end

    alter table(:auctions) do
      remove :links
      remove :discord
    end
  end
end
