defmodule Autolaunch.Repo.Migrations.DropStockLaunchDraftMinimumRaise do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:stock_launch_drafts) do
      remove :minimum_raise
    end
  end

  def down do
    alter table(:stock_launch_drafts) do
      add :minimum_raise, :text
    end
  end
end
