defmodule Autolaunch.Repo.Migrations.PublicListIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:auctions, ["opened_at DESC NULLS LAST", "inserted_at DESC", "id"],
             name: "auctions_public_newest_index"
           )

    create index(:auctions, [:opened_at, :inserted_at, :id], name: "auctions_public_oldest_index")

    create index(:auctions, ["inserted_at DESC", "id"], name: "auctions_home_newest_index")

    create index(:auctions, [:kind, :state], name: "auctions_kind_state_index")

    create index(:tokens, ["graduated_at DESC", "id"], name: "tokens_graduated_newest_index")
  end

  def down do
    drop_if_exists index(:tokens, ["graduated_at DESC", "id"],
                     name: "tokens_graduated_newest_index"
                   )

    drop_if_exists index(:auctions, [:kind, :state], name: "auctions_kind_state_index")

    drop_if_exists index(:auctions, ["inserted_at DESC", "id"],
                     name: "auctions_home_newest_index"
                   )

    drop_if_exists index(:auctions, [:opened_at, :inserted_at, :id],
                     name: "auctions_public_oldest_index"
                   )

    drop_if_exists index(:auctions, ["opened_at DESC NULLS LAST", "inserted_at DESC", "id"],
                     name: "auctions_public_newest_index"
                   )
  end
end
