*
!platform/assets/**
!platform/config/**
!platform/contracts/**
!platform/lib/**
!platform/priv/**
!platform/rel/**
!platform/mix.exs
!platform/mix.lock
!platform/package.json
!platform/package-lock.json
!blog/**

**/.[eE][nN][vV]*
**/node_modules/**
**/_build/**
**/deps/**
