defmodule Autolaunch.Repo.Migrations.AuctionCreatorRequired do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:auctions) do
      modify :creator_human_account_id, :bigint, null: false
    end
  end

  def down do
    alter table(:auctions) do
      modify :creator_human_account_id, :bigint, null: true
    end
  end
end
