defmodule Autolaunch.Repo.Migrations.AutolaunchDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:auctions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :summary, :text
      add :token_symbol, :text
      add :website, :text
      add :image, :text
      add :featured, :boolean, null: false, default: false
      add :state, :text, null: false, default: "created"
      add :opened_at, :utc_datetime_usec
      add :auction_address, :text
      add :quote_token_address, :text
      add :quote_token_symbol, :text
      add :quote_token_decimals, :bigint
      add :current_clearing_price, :text
      add :treasury_address, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :creator_human_account_id,
          references(:human_accounts,
            column: :id,
            name: "auctions_creator_human_account_id_fkey",
            type: :bigint,
            prefix: "public"
          )

      add :treasury_security_report_id, :uuid
    end

    create table(:bid_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action_id, :text, null: false
      add :envelope, :map, null: false
      add :signer, :text, null: false
      add :step, :text, null: false
      add :state, :text, null: false, default: "prepared"
      add :token_approval_transaction_hash, :text
      add :permit2_approval_transaction_hash, :text
      add :bid_transaction_hash, :text
      add :onchain_bid_id, :text
      add :reason, :text
      add :terminal_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "bid_operations_human_account_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:bid_operations, [:action_id],
             name: "bid_operations_unique_action_id_index"
           )

    create unique_index(:bid_operations, [:bid_transaction_hash],
             name: "bid_operations_unique_bid_transaction_hash_index"
           )

    create unique_index(:bid_operations, [:permit2_approval_transaction_hash],
             name: "bid_operations_unique_permit2_approval_transaction_hash_index"
           )

    create unique_index(:bid_operations, [:token_approval_transaction_hash],
             name: "bid_operations_unique_token_approval_transaction_hash_index"
           )

    create unique_index(:bid_operations, [:human_account_id],
             name: "bid_operations_one_open_per_account_index",
             where: "(terminal_at IS NULL)"
           )

    create table(:bids, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bid_id, :text, null: false
      add :owner_address, :text, null: false
      add :amount, :text, null: false
      add :max_price, :text
      add :current_clearing_price, :text
      add :estimated_tokens_if_end_now, :text
      add :status, :text, null: false, default: "active"
      add :exited_at, :utc_datetime_usec
      add :claimed_at, :utc_datetime_usec
      add :auction_address, :text
      add :onchain_bid_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :auction_id,
          references(:auctions,
            column: :id,
            name: "bids_auction_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:bids, [:bid_id], name: "bids_unique_bid_id_index")

    create index(:bids, [:owner_address])

    create index(:bids, [:auction_id])

    create index(:bids, [:status])

    create table(:launch_draft_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :digest, :text, null: false
      add :content_type, :text, null: false
      add :byte_size, :bigint, null: false
      add :bytes, :binary, null: false
      add :original_filename, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "launch_draft_images_human_account_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :launch_draft_id, :uuid, null: false
    end

    create unique_index(:launch_draft_images, [:launch_draft_id],
             name: "launch_draft_images_one_image_per_draft_index"
           )

    create table(:launch_drafts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:launch_draft_images) do
      modify :launch_draft_id,
             references(:launch_drafts,
               column: :id,
               name: "launch_draft_images_launch_draft_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:launch_drafts) do
      add :token_name, :text, null: false, default: ""
      add :symbol, :text, null: false, default: ""
      add :summary, :text
      add :website, :text
      add :image, :text
      add :treasury, :text
      add :treasury_path, :text, null: false, default: "safe"
      add :required_regent_raised, :text
      add :eoa_acknowledgement, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "launch_drafts_human_account_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:launch_drafts, [:human_account_id],
             name: "launch_drafts_one_account_owned_draft_per_human_index"
           )

    alter table(:launch_drafts) do
      add :launch_draft_image_id,
          references(:launch_draft_images,
            column: :id,
            name: "launch_drafts_launch_draft_image_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create index(:launch_drafts, [:human_account_id])

    create index(:launch_drafts, [:launch_draft_image_id])

    create table(:launch_jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :job_id, :text, null: false
      add :status, :text, null: false
      add :step, :text, null: false
      add :agent_id, :text, null: false
      add :agent_name, :text
      add :token_name, :text, null: false
      add :token_symbol, :text, null: false
      add :chain_id, :bigint, null: false
      add :agent_safe_address, :text
      add :auction_address, :text
      add :token_address, :text
      add :hook_address, :text
      add :revenue_share_splitter_address, :text
      add :treasury_address, :text
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :auction_id,
          references(:auctions,
            column: :id,
            name: "launch_jobs_auction_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:launch_jobs, [:job_id], name: "launch_jobs_unique_job_id_index")

    alter table(:launch_jobs) do
      add :treasury_security_report_id, :uuid
    end

    create table(:launch_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action_id, :text, null: false
      add :envelope, :map, null: false
      add :signer, :text, null: false
      add :step, :text, null: false
      add :state, :text, null: false, default: "prepared"
      add :approval_transaction_hash, :text
      add :launch_transaction_hash, :text
      add :result, :map, default: %{}
      add :reason, :text
      add :terminal_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "launch_operations_human_account_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:launch_operations, [:action_id],
             name: "launch_operations_unique_launch_action_id_index"
           )

    create unique_index(:launch_operations, [:approval_transaction_hash],
             name: "launch_operations_unique_launch_approval_hash_index"
           )

    create unique_index(:launch_operations, [:launch_transaction_hash],
             name: "launch_operations_unique_launch_hash_index"
           )

    alter table(:launch_operations) do
      add :launch_draft_id,
          references(:launch_drafts,
            column: :id,
            name: "launch_operations_launch_draft_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:launch_operations, [:human_account_id],
             name: "launch_operations_one_open_per_account_index",
             where: "(terminal_at IS NULL)"
           )

    create table(:payment_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :receiver_address, :text, null: false
      add :label, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subject_id, :uuid, null: false
    end

    create unique_index(:payment_links, [:receiver_address],
             name: "payment_links_unique_receiver_address_index"
           )

    create index(:payment_links, [:subject_id])

    create table(:subject_actions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :owner_address, :text
      add :chain_id, :bigint, null: false
      add :tx_hash, :text
      add :amount, :text
      add :status, :text, null: false, default: "pending"
      add :block_number, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :subject_id, :uuid, null: false
    end

    create table(:subject_wallet_operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action_id, :text, null: false
      add :subject_id, :text, null: false
      add :kind, :text, null: false
      add :envelope, :map, null: false
      add :signer, :text, null: false
      add :step, :text, null: false
      add :state, :text, null: false, default: "prepared"
      add :approval_transaction_hash, :text
      add :action_transaction_hash, :text
      add :result, :map, default: %{}
      add :reason, :text
      add :terminal_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :human_account_id,
          references(:human_accounts,
            column: :id,
            name: "subject_wallet_operations_human_account_id_fkey",
            type: :bigint,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:subject_wallet_operations, [:action_transaction_hash],
             name: "subject_wallet_operations_unique_action_hash_index"
           )

    create unique_index(:subject_wallet_operations, [:action_id],
             name: "subject_wallet_operations_unique_action_id_index"
           )

    create unique_index(:subject_wallet_operations, [:approval_transaction_hash],
             name: "subject_wallet_operations_unique_approval_hash_index"
           )

    create unique_index(:subject_wallet_operations, [:human_account_id, :subject_id],
             name: "subject_wallet_operations_one_open_per_subject_index",
             where: "(terminal_at IS NULL)"
           )

    create table(:subjects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:payment_links) do
      modify :subject_id,
             references(:subjects,
               column: :id,
               name: "payment_links_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subject_actions) do
      modify :subject_id,
             references(:subjects,
               column: :id,
               name: "subject_actions_subject_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subjects) do
      add :subject_id, :text, null: false
      add :subject_kind, :text, null: false
      add :chain_id, :bigint, null: false
      add :token_address, :text
      add :splitter_address, :text
      add :ingress_address, :text
      add :treasury_address, :text
      add :canonical_receiver_address, :text
      add :factory_address, :text
      add :revenue_router_address, :text
      add :creator_address, :text
      add :staker_pool_bps, :bigint
      add :protocol_skim_bps_snapshot, :bigint
      add :current_protocol_skim_bps, :bigint
      add :protocol_fee_usdc_total_raw, :text
      add :regent_emission_total_raw, :text
      add :pending_buyback_usdc_raw, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :treasury_security_report_id, :uuid
    end

    create unique_index(:subjects, [:subject_id], name: "subjects_unique_subject_id_index")

    create table(:tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :symbol, :text, null: false
      add :summary, :text
      add :graduated_at, :utc_datetime_usec, null: false
      add :top_rank, :bigint
      add :subject_id, :text
      add :price_quote, :text
      add :price_source, :text
      add :price_updated_at, :utc_datetime_usec
      add :treasury_address, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :auction_id,
          references(:auctions,
            column: :id,
            name: "tokens_auction_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:tokens, [:auction_id], name: "tokens_unique_auction_index")

    alter table(:tokens) do
      add :treasury_security_report_id, :uuid
    end

    create table(:treasury_security_reports, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:auctions) do
      modify :treasury_security_report_id,
             references(:treasury_security_reports,
               column: :id,
               name: "auctions_treasury_security_report_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:launch_jobs) do
      modify :treasury_security_report_id,
             references(:treasury_security_reports,
               column: :id,
               name: "launch_jobs_treasury_security_report_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:subjects) do
      modify :treasury_security_report_id,
             references(:treasury_security_reports,
               column: :id,
               name: "subjects_treasury_security_report_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tokens) do
      modify :treasury_security_report_id,
             references(:treasury_security_reports,
               column: :id,
               name: "tokens_treasury_security_report_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:treasury_security_reports) do
      add :address, :text, null: false
      add :chain_id, :bigint, null: false
      add :classification, :text, null: false
      add :safe_version, :text
      add :safe_singleton, :text
      add :owner_addresses, {:array, :text}, null: false, default: []
      add :owner_count, :bigint, null: false, default: 0
      add :threshold, :bigint
      add :modules, {:array, :text}, null: false, default: []
      add :guard, :text
      add :fallback_handler, :text
      add :configuration_fingerprint, :text, null: false
      add :source_block_number, :bigint, null: false
      add :source_block_hash, :text, null: false
      add :observed_at, :utc_datetime_usec, null: false
      add :verification_state, :text, null: false
      add :verification_reason, :text, null: false
      add :usdc_evidence, :map
      add :regent_evidence, :map
      add :outbound_evidence, :map
      add :downgrade_state, :text, null: false, default: "none"
      add :prior_verified_fingerprint, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:treasury_security_reports, [:address, :source_block_number])
  end

  def down do
    drop_if_exists index(:treasury_security_reports, [:address, :source_block_number])

    alter table(:treasury_security_reports) do
      remove :updated_at
      remove :inserted_at
      remove :prior_verified_fingerprint
      remove :downgrade_state
      remove :outbound_evidence
      remove :regent_evidence
      remove :usdc_evidence
      remove :verification_reason
      remove :verification_state
      remove :observed_at
      remove :source_block_hash
      remove :source_block_number
      remove :configuration_fingerprint
      remove :fallback_handler
      remove :guard
      remove :modules
      remove :threshold
      remove :owner_count
      remove :owner_addresses
      remove :safe_singleton
      remove :safe_version
      remove :classification
      remove :chain_id
      remove :address
    end

    drop constraint(:tokens, "tokens_treasury_security_report_id_fkey")

    drop constraint(:tokens, "tokens_auction_id_fkey")

    alter table(:tokens) do
      modify :treasury_security_report_id, :uuid
    end

    drop constraint(:subjects, "subjects_treasury_security_report_id_fkey")

    alter table(:subjects) do
      modify :treasury_security_report_id, :uuid
    end

    drop constraint(:launch_jobs, "launch_jobs_treasury_security_report_id_fkey")

    drop constraint(:launch_jobs, "launch_jobs_auction_id_fkey")

    alter table(:launch_jobs) do
      modify :treasury_security_report_id, :uuid
    end

    drop constraint(:auctions, "auctions_treasury_security_report_id_fkey")

    drop constraint(:auctions, "auctions_creator_human_account_id_fkey")

    alter table(:auctions) do
      modify :treasury_security_report_id, :uuid
    end

    drop table(:treasury_security_reports)

    alter table(:tokens) do
      remove :treasury_security_report_id
    end

    drop_if_exists unique_index(:tokens, [:auction_id], name: "tokens_unique_auction_index")

    drop table(:tokens)

    drop_if_exists unique_index(:subjects, [:subject_id],
                     name: "subjects_unique_subject_id_index"
                   )

    alter table(:subjects) do
      remove :treasury_security_report_id
      remove :updated_at
      remove :inserted_at
      remove :pending_buyback_usdc_raw
      remove :regent_emission_total_raw
      remove :protocol_fee_usdc_total_raw
      remove :current_protocol_skim_bps
      remove :protocol_skim_bps_snapshot
      remove :staker_pool_bps
      remove :creator_address
      remove :revenue_router_address
      remove :factory_address
      remove :canonical_receiver_address
      remove :treasury_address
      remove :ingress_address
      remove :splitter_address
      remove :token_address
      remove :chain_id
      remove :subject_kind
      remove :subject_id
    end

    drop constraint(:subject_actions, "subject_actions_subject_id_fkey")

    alter table(:subject_actions) do
      modify :subject_id, :uuid
    end

    drop constraint(:payment_links, "payment_links_subject_id_fkey")

    alter table(:payment_links) do
      modify :subject_id, :uuid
    end

    drop table(:subjects)

    drop constraint(:subject_wallet_operations, "subject_wallet_operations_human_account_id_fkey")

    drop_if_exists unique_index(:subject_wallet_operations, [:human_account_id, :subject_id],
                     name: "subject_wallet_operations_one_open_per_subject_index"
                   )

    drop_if_exists unique_index(:subject_wallet_operations, [:approval_transaction_hash],
                     name: "subject_wallet_operations_unique_approval_hash_index"
                   )

    drop_if_exists unique_index(:subject_wallet_operations, [:action_id],
                     name: "subject_wallet_operations_unique_action_id_index"
                   )

    drop_if_exists unique_index(:subject_wallet_operations, [:action_transaction_hash],
                     name: "subject_wallet_operations_unique_action_hash_index"
                   )

    drop table(:subject_wallet_operations)

    drop table(:subject_actions)

    drop_if_exists index(:payment_links, [:subject_id])

    drop_if_exists unique_index(:payment_links, [:receiver_address],
                     name: "payment_links_unique_receiver_address_index"
                   )

    drop table(:payment_links)

    drop constraint(:launch_operations, "launch_operations_launch_draft_id_fkey")

    drop constraint(:launch_operations, "launch_operations_human_account_id_fkey")

    drop_if_exists unique_index(:launch_operations, [:human_account_id],
                     name: "launch_operations_one_open_per_account_index"
                   )

    alter table(:launch_operations) do
      remove :launch_draft_id
    end

    drop_if_exists unique_index(:launch_operations, [:launch_transaction_hash],
                     name: "launch_operations_unique_launch_hash_index"
                   )

    drop_if_exists unique_index(:launch_operations, [:approval_transaction_hash],
                     name: "launch_operations_unique_launch_approval_hash_index"
                   )

    drop_if_exists unique_index(:launch_operations, [:action_id],
                     name: "launch_operations_unique_launch_action_id_index"
                   )

    drop table(:launch_operations)

    alter table(:launch_jobs) do
      remove :treasury_security_report_id
    end

    drop_if_exists unique_index(:launch_jobs, [:job_id], name: "launch_jobs_unique_job_id_index")

    drop table(:launch_jobs)

    drop_if_exists index(:launch_drafts, [:launch_draft_image_id])

    drop_if_exists index(:launch_drafts, [:human_account_id])

    drop constraint(:launch_drafts, "launch_drafts_launch_draft_image_id_fkey")

    drop constraint(:launch_drafts, "launch_drafts_human_account_id_fkey")

    alter table(:launch_drafts) do
      remove :launch_draft_image_id
    end

    drop_if_exists unique_index(:launch_drafts, [:human_account_id],
                     name: "launch_drafts_one_account_owned_draft_per_human_index"
                   )

    alter table(:launch_drafts) do
      remove :human_account_id
      remove :updated_at
      remove :inserted_at
      remove :eoa_acknowledgement
      remove :required_regent_raised
      remove :treasury_path
      remove :treasury
      remove :image
      remove :website
      remove :summary
      remove :symbol
      remove :token_name
    end

    drop constraint(:launch_draft_images, "launch_draft_images_launch_draft_id_fkey")

    drop constraint(:launch_draft_images, "launch_draft_images_human_account_id_fkey")

    alter table(:launch_draft_images) do
      modify :launch_draft_id, :uuid
    end

    drop table(:launch_drafts)

    drop_if_exists unique_index(:launch_draft_images, [:launch_draft_id],
                     name: "launch_draft_images_one_image_per_draft_index"
                   )

    drop table(:launch_draft_images)

    drop_if_exists index(:bids, [:status])

    drop_if_exists index(:bids, [:auction_id])

    drop_if_exists index(:bids, [:owner_address])

    drop constraint(:bids, "bids_auction_id_fkey")

    drop_if_exists unique_index(:bids, [:bid_id], name: "bids_unique_bid_id_index")

    drop table(:bids)

    drop constraint(:bid_operations, "bid_operations_human_account_id_fkey")

    drop_if_exists unique_index(:bid_operations, [:human_account_id],
                     name: "bid_operations_one_open_per_account_index"
                   )

    drop_if_exists unique_index(:bid_operations, [:token_approval_transaction_hash],
                     name: "bid_operations_unique_token_approval_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_operations, [:permit2_approval_transaction_hash],
                     name: "bid_operations_unique_permit2_approval_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_operations, [:bid_transaction_hash],
                     name: "bid_operations_unique_bid_transaction_hash_index"
                   )

    drop_if_exists unique_index(:bid_operations, [:action_id],
                     name: "bid_operations_unique_action_id_index"
                   )

    drop table(:bid_operations)

    drop table(:auctions)
  end
end
