// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.26;

import {BaseBindings} from "../../src/bindings/BaseBindings.sol";
import {ConditionalVestingEscrowV1} from "../../src/escrow/ConditionalVestingEscrowV1.sol";
import {RegentsAutolaunchFactoryV1} from "../../src/factory/RegentsAutolaunchFactoryV1.sol";
import {RegentFeeHook} from "../../src/hook/RegentFeeHook.sol";
import {PaymentReceiverV1} from "../../src/revenue/PaymentReceiverV1.sol";
import {SubjectSplitterV1} from "../../src/revenue/SubjectSplitterV1.sol";
import {RegentLBPStrategy} from "../../src/strategy/RegentLBPStrategy.sol";
import {Initializable} from "solady/utils/Initializable.sol";
import {AutolaunchFixture} from "../integration/AutolaunchFixture.sol";
import {FrozenSurface} from "./FrozenSurface.sol";

/// @notice `ABI-002` through `ABI-009` and `DEP-016`: the frozen release surface is exactly what the
///         compiler produced, and it is the only surface this system exposes.
/// @dev The authority is `reports/frozen/abi-surface.json`, `reports/frozen/deployable-sizes.json`,
///      and `contracts/autolaunch-release-manifest.json`, all generated by `bin/freeze-artifacts.py`
///      and re-checked byte for byte by `bin/gate.sh`. Every assertion below compares one of those
///      records against something the compiler decided — a function selector, an event selector, a
///      keccak of the canonical signature, or a real deployed clone — so neither side can drift
///      alone.
contract AutolaunchAbiFreezeTest is AutolaunchFixture, FrozenSurface {
    string internal constant FACTORY = "RegentsAutolaunchFactoryV1";
    string internal constant STRATEGY = "RegentLBPStrategy";
    string internal constant HOOK = "RegentFeeHook";
    string internal constant ESCROW = "ConditionalVestingEscrowV1";
    string internal constant SPLITTER = "SubjectSplitterV1";
    string internal constant RECEIVER = "PaymentReceiverV1";

    function setUp() public {
        _loadFrozenSurface();
        _deployAutolaunch();
    }

    // -------------------------------------------------------------------------
    // ABI-002 / ABI-003 — the factory
    // -------------------------------------------------------------------------

    /// @notice `ABI-002`: the factory's public mutation surface is exactly the five `SPEC.md`
    ///         section 4 entry points — no owner transfer, no setter, no upgrade, no arbitrary call.
    function test_ABI_002_FactoryPublicMutationSurfaceIsExact() public view {
        string[] memory frozenLines = _frozenStrings(FACTORY, "mutating_functions");

        string[] memory expected = new string[](5);
        expected[0] = _assertFrozenFunction(
            frozenLines,
            RegentsAutolaunchFactoryV1.launch.selector,
            "launch((string,string,string,string,string,address,address,uint128,uint256))",
            "factory"
        );
        expected[1] = _assertFrozenFunction(
            frozenLines, RegentsAutolaunchFactoryV1.setLaunchFee.selector, "setLaunchFee(uint256)", "factory"
        );
        expected[2] = _assertFrozenFunction(
            frozenLines, RegentsAutolaunchFactoryV1.pauseLaunches.selector, "pauseLaunches()", "factory"
        );
        expected[3] = _assertFrozenFunction(
            frozenLines, RegentsAutolaunchFactoryV1.unpauseLaunches.selector, "unpauseLaunches()", "factory"
        );
        expected[4] = _assertFrozenFunction(
            frozenLines,
            RegentsAutolaunchFactoryV1.createPaymentReceiver.selector,
            "createPaymentReceiver(uint256,address,uint16)",
            "factory"
        );

        _assertSameSet(frozenLines, expected, "factory public mutation surface");
    }

    /// @notice `ABI-003`: `LaunchParams` carries exactly the nine `SPEC.md` fields, in order, at
    ///         exactly those widths.
    /// @dev Two independent proofs of the same shape: the field list the compiler recorded in the
    ///      ABI, and the tuple encoded inside `launch`'s own selector. A reordered, renamed, added,
    ///      removed, or rewidened field fails at least one of them.
    function test_ABI_003_LaunchParamsFieldsAreExact() public view {
        string[] memory frozen = _frozenStrings(FACTORY, "input_structs.launch_params");

        string[9] memory expected = [
            "string name",
            "string symbol",
            "string description",
            "string website",
            "string image",
            "address treasury",
            "address recoveryAdmin",
            "uint128 requiredRegentRaised",
            "uint256 expectedLaunchFee"
        ];

        assertEq(frozen.length, expected.length, "LaunchParams field count");
        for (uint256 i; i < expected.length; ++i) {
            assertEq(frozen[i], expected[i], string.concat("LaunchParams field ", vm.toString(i)));
        }

        assertEq(
            bytes4(keccak256("launch((string,string,string,string,string,address,address,uint128,uint256))")),
            RegentsAutolaunchFactoryV1.launch.selector,
            "the LaunchParams tuple encoded in launch's selector is not the frozen one"
        );
    }

    // -------------------------------------------------------------------------
    // ABI-004 / ABI-005 — the splitter
    // -------------------------------------------------------------------------

    /// @notice `ABI-004`: the splitter's caller-only surface is exactly the six `SPEC.md` section 7
    ///         functions, and every one of them acts for `msg.sender` alone.
    function test_ABI_004_SplitterCallerOnlySurfaceIsExact() public view {
        string[] memory frozenLines = _frozenStrings(SPLITTER, "mutating_functions");

        // The helper reconciles each of the six against its compiler selector as it builds them.
        assertEq(_splitterCallerOnly(frozenLines).length, 6, "the caller-only surface is not six functions");

        // None of the six takes an account argument, so none of them can act for another account.
        string[6] memory noAccountArgument = [
            "stake(uint256)",
            "unstake(uint256)",
            "claim(address)",
            "claimAll()",
            "depositRecognizedRevenue(address,uint256,bytes32)",
            "recognizeSurplusRevenue(address,bytes32)"
        ];
        for (uint256 i; i < noAccountArgument.length; ++i) {
            assertTrue(
                _contains(
                    frozenLines, _functionLine(bytes4(keccak256(bytes(noAccountArgument[i]))), noAccountArgument[i])
                ),
                string.concat("the splitter no longer declares ", noAccountArgument[i])
            );
        }
    }

    /// @notice `ABI-005`: beyond those six the splitter exposes only its one-shot initializer and
    ///         the two administrative recovery functions, and nothing else that mutates.
    function test_ABI_005_SplitterAdministrativeRecoverySurfaceIsExact() public view {
        string[] memory frozenLines = _frozenStrings(SPLITTER, "mutating_functions");

        string[] memory callerOnly = _splitterCallerOnly(frozenLines);
        string[] memory expected = new string[](callerOnly.length + 3);
        for (uint256 i; i < callerOnly.length; ++i) {
            expected[i] = callerOnly[i];
        }
        expected[callerOnly.length] = _assertFrozenFunction(
            frozenLines,
            SubjectSplitterV1.initialize.selector,
            "initialize(address,address,address,address,address,address,address)",
            "splitter"
        );
        expected[callerOnly.length + 1] = _assertFrozenFunction(
            frozenLines,
            SubjectSplitterV1.recoverUnsupportedToken.selector,
            "recoverUnsupportedToken(address,uint256)",
            "splitter"
        );
        expected[callerOnly.length + 2] = _assertFrozenFunction(
            frozenLines, SubjectSplitterV1.recoverForcedETH.selector, "recoverForcedETH(uint256)", "splitter"
        );

        _assertSameSet(frozenLines, expected, "splitter complete mutating surface");
    }

    // -------------------------------------------------------------------------
    // ABI-006 — the receiver
    // -------------------------------------------------------------------------

    /// @notice `ABI-006`: the receiver's surface is exactly `pay`, `sweep`, `setReceiverNote`, the
    ///         two recovery functions, and its one-shot initializer.
    function test_ABI_006_ReceiverSurfaceIsExact() public view {
        string[] memory frozenLines = _frozenStrings(RECEIVER, "mutating_functions");

        string[] memory expected = new string[](6);
        expected[0] = _assertFrozenFunction(
            frozenLines, PaymentReceiverV1.pay.selector, "pay(address,uint256,bytes32)", "receiver"
        );
        expected[1] =
            _assertFrozenFunction(frozenLines, PaymentReceiverV1.sweep.selector, "sweep(address,bytes32)", "receiver");
        expected[2] = _assertFrozenFunction(
            frozenLines, PaymentReceiverV1.setReceiverNote.selector, "setReceiverNote(bytes32)", "receiver"
        );
        expected[3] = _assertFrozenFunction(
            frozenLines,
            PaymentReceiverV1.recoverUnsupportedToken.selector,
            "recoverUnsupportedToken(address,uint256)",
            "receiver"
        );
        expected[4] = _assertFrozenFunction(
            frozenLines, PaymentReceiverV1.recoverForcedETH.selector, "recoverForcedETH(uint256)", "receiver"
        );
        expected[5] = _assertFrozenFunction(
            frozenLines,
            PaymentReceiverV1.initialize.selector,
            "initialize(address,address,uint16,address,bool)",
            "receiver"
        );

        _assertSameSet(frozenLines, expected, "receiver mutating surface");
    }

    // -------------------------------------------------------------------------
    // ABI-007 — events
    // -------------------------------------------------------------------------

    /// @notice `ABI-007`: every production event's topic, indexed-field set, and exact value widths
    ///         equal what the compiler produced and what the frozen surface records, in both
    ///         directions.
    /// @dev This claim is compiler and frozen-artifact truth only. It makes no statement about any
    ///      downstream consumer's parity: the Ash watcher's own coverage is separate product work.
    ///      Width freezing is exact because a topic is the keccak of the canonical signature, so
    ///      `uint128` becoming `uint256` changes the topic and fails here.
    function test_ABI_007_EventTopicsIndexingAndWidthsAreFrozen() public view {
        _assertEvents(FACTORY, _factoryEvents());
        _assertEvents(STRATEGY, _strategyEvents());
        _assertEvents(HOOK, _hookEvents());
        _assertEvents(ESCROW, _escrowEvents());
        _assertEvents(SPLITTER, _splitterEvents());
        _assertEvents(RECEIVER, _receiverEvents());
    }

    // -------------------------------------------------------------------------
    // ABI-008 — one-shot clone initializers
    // -------------------------------------------------------------------------

    /// @notice `ABI-008`: every clone initializer runs exactly once and can never be re-run, and the
    ///         three implementations themselves are permanently uninitializable.
    /// @dev A direct production test, not an ABI reading: one-shot behaviour is runtime behaviour.
    ///      Each clone is the real one this graph created through its real production caller.
    function test_ABI_008_CloneInitializersRunExactlyOnce() public {
        Launched memory launched = _defaultLaunch();
        _bidToGraduation(launched, 2_000e18);
        strategy.migrate(address(launched.auction));
        RegentLBPStrategy.Distribution memory d = _distribution(launched);

        // The escrow clone: initialized by the factory during `launch`.
        vm.expectRevert(Initializable.InvalidInitialization.selector);
        ConditionalVestingEscrowV1(address(launched.escrow))
            .initialize(address(launched.subject), treasury, address(strategy));
        vm.prank(outsider);
        vm.expectRevert(Initializable.InvalidInitialization.selector);
        ConditionalVestingEscrowV1(address(launched.escrow)).initialize(outsider, outsider, outsider);

        // The splitter clone: initialized by the strategy during graduation.
        vm.prank(outsider);
        vm.expectRevert(Initializable.InvalidInitialization.selector);
        SubjectSplitterV1(d.splitter)
            .initialize(
                address(usdc),
                address(regent),
                address(launched.subject),
                address(liveStaking),
                governance,
                outsider,
                address(recoveryAdmin)
            );

        // The canonical receiver clone, and a custom one the factory made afterwards.
        address custom = factory.createPaymentReceiver(launched.launchId, outsider, 100);
        address[2] memory receivers = [d.receiver, custom];
        for (uint256 i; i < receivers.length; ++i) {
            vm.prank(outsider);
            vm.expectRevert(Initializable.InvalidInitialization.selector);
            PaymentReceiverV1(payable(receivers[i])).initialize(d.splitter, outsider, 0, outsider, false);
        }

        // The three implementations disabled their initializers at construction, so no clone target
        // can ever hold a launch itself.
        vm.expectRevert(Initializable.InvalidInitialization.selector);
        escrowImplementation.initialize(address(launched.subject), treasury, address(strategy));
        vm.expectRevert(Initializable.InvalidInitialization.selector);
        splitterImplementation.initialize(
            address(usdc),
            address(regent),
            address(launched.subject),
            address(liveStaking),
            governance,
            treasury,
            address(recoveryAdmin)
        );
        vm.expectRevert(Initializable.InvalidInitialization.selector);
        receiverImplementation.initialize(d.splitter, treasury, 0, treasury, false);
    }

    // -------------------------------------------------------------------------
    // ABI-009 — no superseded interface survives
    // -------------------------------------------------------------------------

    /// @notice `ABI-009`: no Safe, ERC-8004, registry, flush, or retry entry point from the
    ///         superseded Autolaunch graph appears anywhere in the frozen surface or in any
    ///         implementation runtime.
    /// @dev The frozen surface is the complete-surface authority, so the absence proof is a name
    ///      scan over it. The runtime scan is a second, independent check and is run only against
    ///      real implementation runtimes: a 44-byte minimal-proxy clone carries no dispatcher at
    ///      all, so scanning one would prove nothing about the surface it forwards to.
    function test_ABI_009_NoObsoleteSupersededInterfaceRemains() public view {
        string[13] memory obsolete = [
            "setSafe",
            "safe",
            "registerIdentity",
            "identityRegistry",
            "erc8004Identity",
            "registry",
            "setRegistry",
            "flush",
            "flushFees",
            "retry",
            "retryMigration",
            "setRetryMode",
            "recoverMigration"
        ];

        string[6] memory contractNames = [FACTORY, STRATEGY, HOOK, ESCROW, SPLITTER, RECEIVER];
        for (uint256 c; c < contractNames.length; ++c) {
            string[] memory functions = _frozenStrings(contractNames[c], "functions");
            for (uint256 i; i < obsolete.length; ++i) {
                assertFalse(
                    _declaresFunctionNamed(functions, obsolete[i]),
                    string.concat(contractNames[c], " still declares ", obsolete[i])
                );
            }
        }

        address[6] memory runtimes = [
            address(factory),
            address(strategy),
            address(hook),
            address(escrowImplementation),
            address(splitterImplementation),
            address(receiverImplementation)
        ];
        string[4] memory obsoleteSignatures =
            ["setSafe(address)", "registerIdentity(address,bytes32)", "flushFees(address)", "retryMigration(address)"];
        for (uint256 r; r < runtimes.length; ++r) {
            bytes memory runtime = runtimes[r].code;
            assertGt(runtime.length, 44, "a clone runtime cannot be the ABI authority");
            for (uint256 i; i < obsoleteSignatures.length; ++i) {
                assertFalse(
                    _carriesSelector(runtime, bytes4(keccak256(bytes(obsoleteSignatures[i])))),
                    string.concat("a runtime dispatcher still carries ", obsoleteSignatures[i])
                );
            }
        }
    }

    // -------------------------------------------------------------------------
    // DEP-016 — the frozen manifest
    // -------------------------------------------------------------------------

    /// @notice `DEP-016`: the frozen release manifest records the identities production actually
    ///         admits, and records no deployment that does not exist.
    /// @dev `bin/freeze-artifacts.py check` inside `bin/gate.sh` is what proves the manifest was
    ///      regenerated from this build and that every `src/**` byte still equals the pre-edit C4
    ///      baseline; that run writes this claim's verified receipt line. This test is the
    ///      independent Solidity side: the manifest's build identity, its complete-surface
    ///      allowlist, its clone derivation, and its deployment-pending discipline are compared
    ///      against the production constants and a real clone.
    function test_DEP_016_FrozenManifestRecordsTheAdmittedIdentitiesAndNoDeployment() public {
        string memory manifest = vm.readFile(MANIFEST_PATH);

        // Nothing in this repository is deployed. Every Regent address is null.
        string[6] memory allowlist = [FACTORY, STRATEGY, HOOK, ESCROW, SPLITTER, RECEIVER];
        for (uint256 i; i < allowlist.length; ++i) {
            assertEq(
                vm.parseJsonString(manifest, string.concat(".contracts.", allowlist[i], ".deployment.status")),
                "deployment_pending",
                string.concat(allowlist[i], " claims a deployment")
            );
            assertTrue(
                vm.keyExistsJson(manifest, string.concat(".contracts.", allowlist[i], ".abi_file")),
                string.concat(allowlist[i], " has no frozen ABI file")
            );
        }
        string[] memory frozenAllowlist = vm.parseJsonStringArray(manifest, ".surface_allowlist");
        assertEq(frozenAllowlist.length, allowlist.length, "the complete-surface allowlist changed size");

        // Every external binding's runtime fact is still unproven and marked so.
        assertEq(
            vm.parseJsonString(manifest, ".bindings.pool_manager.status"),
            "fork_pending",
            "an external runtime fact was recorded without fork evidence"
        );
        assertEq(
            vm.parseJsonBytes32(manifest, ".bindings.cca_factory.runtime_code_hash"),
            BaseBindings.CCA_FACTORY_RUNTIME_CODE_HASH,
            "the manifest's CCA admission hash is not the compiled binding's"
        );
        assertEq(
            vm.parseJsonAddress(manifest, ".bindings.cca_factory.address"),
            BaseBindings.CCA_FACTORY,
            "the manifest binds a different CCA factory than the compiled binding"
        );

        // The clone derivation the manifest publishes is the one a real clone actually presents.
        Launched memory launched = _defaultLaunch();
        assertEq(
            vm.parseJsonUint(manifest, string.concat(".clones.", ESCROW, ".runtime_bytes")),
            address(launched.escrow).code.length,
            "the manifest's clone runtime length is not a real clone's"
        );
        assertEq(
            address(launched.escrow).codehash,
            strategy.escrowCloneCodehash(),
            "the strategy admits a different clone shape than the one it created"
        );

        // The manifest's build identity is the specification-governed one the gate already proved.
        assertEq(vm.parseJsonUint(manifest, ".build.optimizer_runs"), 200, "manifest optimizer runs");
        assertEq(vm.parseJsonString(manifest, ".build.evm_version"), "cancun", "manifest EVM version");
        assertEq(vm.parseJsonUint(manifest, ".chain.id"), 8453, "manifest chain id");
    }

    // -------------------------------------------------------------------------
    // helpers
    // -------------------------------------------------------------------------

    function _splitterCallerOnly(string[] memory frozenLines) private view returns (string[] memory expected) {
        expected = new string[](6);
        expected[0] = _assertFrozenFunction(frozenLines, SubjectSplitterV1.stake.selector, "stake(uint256)", "splitter");
        expected[1] =
            _assertFrozenFunction(frozenLines, SubjectSplitterV1.unstake.selector, "unstake(uint256)", "splitter");
        expected[2] = _assertFrozenFunction(frozenLines, SubjectSplitterV1.claim.selector, "claim(address)", "splitter");
        expected[3] = _assertFrozenFunction(frozenLines, SubjectSplitterV1.claimAll.selector, "claimAll()", "splitter");
        expected[4] = _assertFrozenFunction(
            frozenLines,
            SubjectSplitterV1.depositRecognizedRevenue.selector,
            "depositRecognizedRevenue(address,uint256,bytes32)",
            "splitter"
        );
        expected[5] = _assertFrozenFunction(
            frozenLines,
            SubjectSplitterV1.recognizeSurplusRevenue.selector,
            "recognizeSurplusRevenue(address,bytes32)",
            "splitter"
        );
    }

    function _assertEvents(string memory contractName, FrozenEvent[] memory declared) private view {
        string[] memory frozenLines = _frozenStrings(contractName, "events");
        string[] memory expected = new string[](declared.length);
        for (uint256 i; i < declared.length; ++i) {
            expected[i] = _assertFrozenEvent(frozenLines, declared[i], contractName);
        }
        _assertSameSet(frozenLines, expected, string.concat(contractName, " events"));
    }

    function _factoryEvents() private pure returns (FrozenEvent[] memory events) {
        events = new FrozenEvent[](6);
        events[0] = FrozenEvent(
            RegentsAutolaunchFactoryV1.LaunchCreated.selector,
            "LaunchCreated(uint256,address,address,address,address,address,address,uint128,uint64,uint64)",
            3
        );
        events[1] =
            FrozenEvent(RegentsAutolaunchFactoryV1.LaunchFeeUpdated.selector, "LaunchFeeUpdated(uint256,uint256)", 0);
        events[2] = FrozenEvent(
            RegentsAutolaunchFactoryV1.LaunchFeeCollected.selector,
            "LaunchFeeCollected(uint256,address,address,uint256)",
            2
        );
        events[3] = FrozenEvent(RegentsAutolaunchFactoryV1.LaunchesPaused.selector, "LaunchesPaused()", 0);
        events[4] = FrozenEvent(RegentsAutolaunchFactoryV1.LaunchesUnpaused.selector, "LaunchesUnpaused()", 0);
        events[5] = FrozenEvent(
            RegentsAutolaunchFactoryV1.PaymentReceiverCreated.selector,
            "PaymentReceiverCreated(uint256,address,address,address,uint16)",
            3
        );
    }

    function _strategyEvents() private pure returns (FrozenEvent[] memory events) {
        events = new FrozenEvent[](4);
        events[0] = FrozenEvent(RegentLBPStrategy.HookBound.selector, "HookBound(address)", 1);
        events[1] = FrozenEvent(
            RegentLBPStrategy.DistributionCreated.selector,
            "DistributionCreated(uint256,address,address,address,address,uint64,uint64,uint128,uint128)",
            3
        );
        events[2] = FrozenEvent(RegentLBPStrategy.LaunchRetired.selector, "LaunchRetired(address,address,uint128)", 2);
        events[3] = FrozenEvent(
            RegentLBPStrategy.LaunchGraduated.selector,
            "LaunchGraduated(address,address,bytes32,address,address,uint160,uint256,uint128,uint128)",
            3
        );
    }

    function _hookEvents() private pure returns (FrozenEvent[] memory events) {
        events = new FrozenEvent[](2);
        events[0] = FrozenEvent(RegentFeeHook.PoolRegistered.selector, "PoolRegistered(bytes32,address,address)", 3);
        events[1] = FrozenEvent(
            RegentFeeHook.SwapFeeSettled.selector, "SwapFeeSettled(bytes32,address,uint256,uint256,bool,bool)", 2
        );
    }

    function _escrowEvents() private pure returns (FrozenEvent[] memory events) {
        events = new FrozenEvent[](7);
        events[0] = FrozenEvent(
            ConditionalVestingEscrowV1.EscrowInitialized.selector, "EscrowInitialized(address,address,address)", 3
        );
        events[1] = FrozenEvent(
            ConditionalVestingEscrowV1.GraduatedUnsoldSubjectSwept.selector,
            "GraduatedUnsoldSubjectSwept(address,uint256)",
            1
        );
        events[2] =
            FrozenEvent(ConditionalVestingEscrowV1.VestingActivated.selector, "VestingActivated(uint64,uint256)", 0);
        events[3] =
            FrozenEvent(ConditionalVestingEscrowV1.SubjectReleased.selector, "SubjectReleased(address,uint256)", 1);
        events[4] = FrozenEvent(ConditionalVestingEscrowV1.LaunchFailed.selector, "LaunchFailed(address,uint256)", 1);
        events[5] = FrozenEvent(
            ConditionalVestingEscrowV1.LateFailedSubjectRetired.selector, "LateFailedSubjectRetired(uint256)", 0
        );
        events[6] = FrozenEvent(Initializable.Initialized.selector, "Initialized(uint64)", 0);
    }

    function _splitterEvents() private pure returns (FrozenEvent[] memory events) {
        events = new FrozenEvent[](8);
        events[0] = FrozenEvent(
            SubjectSplitterV1.SplitterInitialized.selector,
            "SplitterInitialized(address,address,address,address,address,address,address)",
            3
        );
        events[1] = FrozenEvent(SubjectSplitterV1.Staked.selector, "Staked(address,uint256)", 1);
        events[2] = FrozenEvent(SubjectSplitterV1.Unstaked.selector, "Unstaked(address,uint256)", 1);
        events[3] = FrozenEvent(SubjectSplitterV1.Claimed.selector, "Claimed(address,address,uint256)", 2);
        events[4] = FrozenEvent(
            SubjectSplitterV1.RevenueRecognized.selector,
            "RevenueRecognized(address,address,bytes32,uint256,uint256,uint256,bool)",
            3
        );
        events[5] = FrozenEvent(
            SubjectSplitterV1.UnsupportedTokenRecovered.selector,
            "UnsupportedTokenRecovered(address,address,uint256)",
            2
        );
        events[6] = FrozenEvent(SubjectSplitterV1.ForcedEthRecovered.selector, "ForcedEthRecovered(address,uint256)", 1);
        events[7] = FrozenEvent(Initializable.Initialized.selector, "Initialized(uint64)", 0);
    }

    function _receiverEvents() private pure returns (FrozenEvent[] memory events) {
        events = new FrozenEvent[](6);
        events[0] = FrozenEvent(
            PaymentReceiverV1.ReceiverInitialized.selector, "ReceiverInitialized(address,address,uint16,address)", 3
        );
        events[1] =
            FrozenEvent(PaymentReceiverV1.ReceiverNoteUpdated.selector, "ReceiverNoteUpdated(bytes32,bytes32)", 0);
        events[2] = FrozenEvent(
            PaymentReceiverV1.PaymentRouted.selector,
            "PaymentRouted(bytes32,bytes32,address,uint256,uint256,uint256)",
            3
        );
        events[3] = FrozenEvent(
            PaymentReceiverV1.UnsupportedTokenRecovered.selector,
            "UnsupportedTokenRecovered(address,address,uint256)",
            2
        );
        events[4] = FrozenEvent(PaymentReceiverV1.ForcedEthRecovered.selector, "ForcedEthRecovered(address,uint256)", 1);
        events[5] = FrozenEvent(Initializable.Initialized.selector, "Initialized(uint64)", 0);
    }
}
