defmodule AutolaunchWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :autolaunch

  # A connected mount reads the cookie the socket handshake carried, so the
  # transport must decode it with the same options the request plug runs with.
  @session_options {Application, :fetch_env!, [:autolaunch, :session_options]}

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  plug AutolaunchWeb.Plugs.CanonicalHost

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :autolaunch,
    gzip: not code_reloading?,
    only: AutolaunchWeb.static_paths(),
    only_matching:
      for(
        path <- AutolaunchWeb.static_paths(),
        Path.extname(path) != "",
        do: Path.rootname(path) <> "-"
      ),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    # The migration ledger lives in autolaunch_app, as `mix db.setup` records it.
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :autolaunch, prefix: "autolaunch_app"
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug :refuse_blocked

  # One budget per client address, shared by the health check, every /api
  # address and the share pictures, answered or not. Every answer says what is left of it; past it the
  # answer is 429 with Retry-After. The auction list has a second, smaller
  # budget of its own.
  plug :limit_rate

  plug AutolaunchWeb.Prelaunch

  # Before the parsers, so a body they refuse on an /api address is answered
  # in JSON like every other API error.
  plug RegentAgentAccess.Plug,
    documents: &AutolaunchWeb.PublicDocuments.document/1,
    guide: "/llms.txt"

  plug AutolaunchWeb.Plugs.Parsers,
    body_reader: {RegentIdentity.BodyReader, :read_body, []},
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug AutolaunchWeb.Plugs.LaunchImage
  plug AutolaunchWeb.Plugs.RuntimeSession
  plug AutolaunchWeb.Router

  @rate_limit RegentAgentAccess.RateLimit.init(
                policy: "default",
                limit: 120,
                window: 60,
                admit: &Autolaunch.Accounts.RequestRateLimiter.admit/3,
                key: &AutolaunchWeb.ClientAddress.key/1
              )

  # The auction list is answered from a five-second keep, so reading it more
  # often than every five seconds returns the same list.
  @list_rate_limit RegentAgentAccess.RateLimit.init(
                     policy: "auction-list",
                     limit: 6,
                     window: 60,
                     admit: &Autolaunch.Accounts.RequestRateLimiter.admit/3,
                     key: &AutolaunchWeb.ClientAddress.key/1
                   )

  # Addresses refused outright. 43.160.222.210 read the auction list every
  # 2.3 seconds around the clock (founder decision, 9 October 2026).
  @blocked [{43, 160, 222, 210}]

  defp refuse_blocked(conn, _opts) do
    {address, _source} = AutolaunchWeb.ClientAddress.key(conn)

    if address in @blocked do
      conn
      |> put_status(:forbidden)
      |> Phoenix.Controller.json(
        RegentAgentAccess.Recovery.json("Forbidden", "This address may not use this site.")
      )
      |> halt()
    else
      conn
    end
  end

  defp limit_rate(%Plug.Conn{method: "GET", path_info: ["api", "v1", "auctions"]} = conn, _opts) do
    case RegentAgentAccess.RateLimit.call(conn, @rate_limit) do
      %Plug.Conn{halted: true} = limited -> limited
      counted -> RegentAgentAccess.RateLimit.call(counted, @list_rate_limit)
    end
  end

  defp limit_rate(%Plug.Conn{path_info: ["healthz"]} = conn, _opts),
    do: RegentAgentAccess.RateLimit.call(conn, @rate_limit)

  defp limit_rate(%Plug.Conn{path_info: ["api" | _]} = conn, _opts),
    do: RegentAgentAccess.RateLimit.call(conn, @rate_limit)

  # A share picture is drawn on the first request for each version of it, so
  # the pictures share the API's budget.
  defp limit_rate(%Plug.Conn{path_info: [kind, _symbol, _tail, "share.png"]} = conn, _opts)
       when kind in ["auctions", "tokens"],
       do: RegentAgentAccess.RateLimit.call(conn, @rate_limit)

  defp limit_rate(conn, _opts), do: conn
end
