defmodule AutolaunchWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :autolaunch

  # A connected mount reads the cookie the socket handshake carried, so the
  # transport must decode it with the same options the request plug runs with.
  @session_options {Application, :fetch_env!, [:autolaunch, :session_options]}

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  plug AutolaunchWeb.Plugs.CanonicalHost

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :autolaunch,
    gzip: not code_reloading?,
    only: AutolaunchWeb.static_paths(),
    only_matching:
      for(
        path <- AutolaunchWeb.static_paths(),
        Path.extname(path) != "",
        do: Path.rootname(path) <> "-"
      ),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug AshPhoenix.Plug.CheckCodegenStatus
    # The migration ledger lives in autolaunch_app, as `mix db.setup` records it.
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :autolaunch, prefix: "autolaunch_app"
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # One budget per client address, shared by the health check and every /api
  # address, answered or not. Every answer says what is left of it; past it the
  # answer is 429 with Retry-After.
  plug :limit_rate

  plug AutolaunchWeb.Prelaunch

  # Before the parsers, so a body they refuse on an /api address is answered
  # in JSON like every other API error.
  plug RegentAgentAccess.Plug,
    documents: &AutolaunchWeb.PublicDocuments.document/1,
    guide: "/llms.txt"

  plug AutolaunchWeb.Plugs.Parsers,
    body_reader: {RegentIdentity.BodyReader, :read_body, []},
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug AutolaunchWeb.Plugs.LaunchImage
  plug AutolaunchWeb.Plugs.RuntimeSession
  plug AutolaunchWeb.Router

  @rate_limit RegentAgentAccess.RateLimit.init(
                policy: "default",
                limit: 120,
                window: 60,
                admit: &Autolaunch.Accounts.RequestRateLimiter.admit/3,
                key: &AutolaunchWeb.ClientAddress.key/1
              )

  defp limit_rate(%Plug.Conn{path_info: ["healthz"]} = conn, _opts),
    do: RegentAgentAccess.RateLimit.call(conn, @rate_limit)

  defp limit_rate(%Plug.Conn{path_info: ["api" | _]} = conn, _opts),
    do: RegentAgentAccess.RateLimit.call(conn, @rate_limit)

  defp limit_rate(conn, _opts), do: conn
end
