// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.26;

import {BaseBindings} from "../../src/bindings/BaseBindings.sol";
import {ConditionalVestingEscrowV1} from "../../src/escrow/ConditionalVestingEscrowV1.sol";
import {RegentsAutolaunchFactoryV1} from "../../src/factory/RegentsAutolaunchFactoryV1.sol";
import {RegentFeeHook} from "../../src/hook/RegentFeeHook.sol";
import {PaymentReceiverV1} from "../../src/revenue/PaymentReceiverV1.sol";
import {SubjectSplitterV1} from "../../src/revenue/SubjectSplitterV1.sol";
import {RegentLBPStrategy} from "../../src/strategy/RegentLBPStrategy.sol";
import {LibClone} from "solady/utils/LibClone.sol";
import {UERC20Factory} from "uerc20-factory/factories/UERC20Factory.sol";
import {UERC20} from "uerc20-factory/tokens/UERC20.sol";
import {AutolaunchFixture} from "../integration/AutolaunchFixture.sol";

/// @notice `GAS-001` and `GAS-002`: every deployable byte this release needs fits, with the exact
///         margin and the exact EVM code identity the frozen record publishes.
/// @dev The frozen authority is `reports/frozen/deployable-sizes.json`, generated by
///      `bin/freeze-artifacts.py` from the compiler artifacts and re-checked by `bin/gate.sh`.
///      Each recorded number is compared here against a value Solidity derives on its own: a
///      deployed contract's real runtime length, its real `EXTCODEHASH`, the creation code the
///      compiler emits, the exact ABI head the deployment packet appends for that constructor,
///      and — for clones — Solady's own initcode. `EIP-170` bounds runtime; `EIP-3860` bounds
///      creation code plus its constructor arguments, which the compiler's size report excludes.
///
///      Code identity is EVM-native. `runtime_keccak256` is what `EXTCODEHASH` returns for a
///      deployed instance *when the artifact carries no immutable references*, which is exactly
///      the identity `RegentsAutolaunchFactoryV1` admits its four dependencies by. The record
///      says per contract whether that holds, and this test proves the flag honest in both
///      directions rather than taking it on trust. The SHA-256 beside it is a packet-diffing
///      digest and is never an admission identity.
contract AutolaunchDeployableSizesTest is AutolaunchFixture {
    uint256 internal constant EIP170_RUNTIME_LIMIT = 24_576;
    uint256 internal constant EIP3860_INITCODE_LIMIT = 49_152;

    /// @notice The repository budget: no deployable contract may sit closer than this to EIP-170.
    /// @dev `regent-worker-contracts` requires at least 1,000 runtime bytes of headroom when no
    ///      stricter rule is recorded, and none is.
    uint256 internal constant REQUIRED_RUNTIME_HEADROOM = 1_000;

    string internal constant SIZES_PATH = "reports/frozen/deployable-sizes.json";

    string private _sizes;

    function setUp() public {
        _sizes = vm.readFile(SIZES_PATH);
        _deployAutolaunch();
    }

    /// @notice `GAS-001`: every deployable contract's runtime is inside EIP-170 with the recorded
    ///         margin, and the recorded margin is the real deployed length's.
    function test_GAS_001_RuntimeSizesAreWithinEip170WithMargin() public {
        assertEq(vm.parseJsonUint(_sizes, ".limits.eip170_runtime_bytes"), EIP170_RUNTIME_LIMIT, "EIP-170 limit");

        _assertRuntime(0, "RegentsAutolaunchFactoryV1", address(factory));
        _assertRuntime(1, "RegentLBPStrategy", address(strategy));
        _assertRuntime(2, "RegentFeeHook", address(hook));
        _assertRuntime(3, "ConditionalVestingEscrowV1", address(escrowImplementation));
        _assertRuntime(4, "SubjectSplitterV1", address(splitterImplementation));
        _assertRuntime(5, "PaymentReceiverV1", address(receiverImplementation));

        // The pinned UERC20 factory the ceremony also deploys, and the per-launch SUBJECT build
        // the pinned factory deploys inside every launch. Both are recorded as deployment-pending
        // dependency builds with their own margins and code identity.
        _assertDependencyRuntime(0, "UERC20Factory", address(uerc20Factory), true);

        Launched memory launched = _defaultLaunch();
        _assertDependencyRuntime(1, "UERC20", address(launched.subject), false);

        // The UERC20 factory is admitted by exactly this EVM code identity, so the frozen record
        // and the production constant must be the same hash as the deployed factory's own.
        assertEq(
            vm.parseJsonBytes32(_sizes, ".dependency_contracts[0].runtime_keccak256"),
            factory.UERC20_FACTORY_RUNTIME_CODE_HASH(),
            "the frozen UERC20 factory identity is not the one the production constructor admits"
        );

        // Every clone this graph creates is the fixed 44-byte minimal proxy the frozen template
        // describes, measured on a real clone rather than assumed, and its EVM codehash is the one
        // the strategy derives from the implementation it admits.
        uint256 recordedCloneRuntime = vm.parseJsonUint(_sizes, ".clone_runtime_template.runtime_bytes");
        assertEq(address(launched.escrow).code.length, recordedCloneRuntime, "a real clone is not the frozen length");
        assertEq(address(launched.escrow).codehash, strategy.escrowCloneCodehash(), "a real clone's 44-byte identity");
        assertLt(
            recordedCloneRuntime + REQUIRED_RUNTIME_HEADROOM, EIP170_RUNTIME_LIMIT, "the clone runtime has no headroom"
        );

        // Each clone implementation's frozen identity is the exact runtime hash the factory admits
        // it by, and the exact hash the deployed implementation presents.
        bytes32[3] memory admitted = [
            factory.ESCROW_IMPLEMENTATION_RUNTIME_CODE_HASH(),
            factory.SPLITTER_IMPLEMENTATION_RUNTIME_CODE_HASH(),
            factory.RECEIVER_IMPLEMENTATION_RUNTIME_CODE_HASH()
        ];
        address[3] memory implementations =
            [address(escrowImplementation), address(splitterImplementation), address(receiverImplementation)];
        for (uint256 i; i < admitted.length; ++i) {
            bytes32 recorded = vm.parseJsonBytes32(
                _sizes, string.concat(".clones[", vm.toString(i), "].implementation_runtime_keccak256")
            );
            assertEq(recorded, admitted[i], "a frozen clone implementation identity is not the admitted one");
            assertEq(implementations[i].codehash, admitted[i], "a deployed implementation is not the admitted runtime");
            assertEq(
                vm.parseJsonUint(_sizes, string.concat(".clones[", vm.toString(i), "].runtime_bytes")),
                recordedCloneRuntime,
                "a clone row records a different 44-byte runtime length"
            );
        }
    }

    /// @notice `GAS-002`: every deployment's creation code plus its exact ABI-encoded constructor
    ///         arguments is inside EIP-3860 with the recorded margin.
    function test_GAS_002_InitcodeSizesAreWithinEip3860WithMargin() public view {
        assertEq(vm.parseJsonUint(_sizes, ".limits.eip3860_initcode_bytes"), EIP3860_INITCODE_LIMIT, "EIP-3860 limit");

        _assertInitcode(
            0,
            "RegentsAutolaunchFactoryV1",
            type(RegentsAutolaunchFactoryV1).creationCode.length,
            abi.encode(
                address(uerc20Factory),
                address(escrowImplementation),
                address(splitterImplementation),
                address(receiverImplementation),
                hookSalt
            )
            .length
        );
        _assertInitcode(
            1,
            "RegentLBPStrategy",
            type(RegentLBPStrategy).creationCode.length,
            abi.encode(
                address(factory),
                address(escrowImplementation),
                address(splitterImplementation),
                address(receiverImplementation)
            )
            .length
        );
        _assertInitcode(
            2,
            "RegentFeeHook",
            type(RegentFeeHook).creationCode.length,
            abi.encode(BaseBindings.POOL_MANAGER, address(strategy)).length
        );
        _assertInitcode(3, "ConditionalVestingEscrowV1", type(ConditionalVestingEscrowV1).creationCode.length, 0);
        _assertInitcode(4, "SubjectSplitterV1", type(SubjectSplitterV1).creationCode.length, 0);
        _assertInitcode(5, "PaymentReceiverV1", type(PaymentReceiverV1).creationCode.length, 0);

        // The pinned dependency builds. The UERC20 factory takes no constructor arguments, and a
        // per-launch UERC20's are encoded by that factory rather than by any deployment packet, so
        // both are recorded as creation length and margin without an exact ABI head.
        _assertDependencyInitcode(0, "UERC20Factory", type(UERC20Factory).creationCode.length);
        _assertDependencyInitcode(1, "UERC20", type(UERC20).creationCode.length);

        // A clone's own deployment initcode is Solady's, so it is measured rather than recorded.
        address[3] memory implementations =
            [address(escrowImplementation), address(splitterImplementation), address(receiverImplementation)];
        uint256 cloneRuntime = vm.parseJsonUint(_sizes, ".clone_runtime_template.runtime_bytes");
        for (uint256 i; i < implementations.length; ++i) {
            uint256 initcode = LibClone.initCode(implementations[i]).length;
            assertGt(initcode, cloneRuntime, "clone initcode must carry the runtime plus its deploy prologue");
            assertLe(initcode, EIP3860_INITCODE_LIMIT, "a clone initcode exceeds EIP-3860");
        }
    }

    // -------------------------------------------------------------------------
    // helpers
    // -------------------------------------------------------------------------

    function _assertRuntime(uint256 index, string memory name, address deployed) private view {
        string memory at = string.concat(".contracts[", vm.toString(index), "]");
        assertEq(vm.parseJsonString(_sizes, string.concat(at, ".contract")), name, "frozen size row order");

        uint256 recorded = vm.parseJsonUint(_sizes, string.concat(at, ".runtime_bytes"));
        uint256 margin = vm.parseJsonUint(_sizes, string.concat(at, ".runtime_margin_bytes"));

        assertEq(deployed.code.length, recorded, string.concat(name, ": the deployed runtime is not the frozen length"));
        assertEq(recorded + margin, EIP170_RUNTIME_LIMIT, string.concat(name, ": the frozen margin does not close"));
        assertGe(margin, REQUIRED_RUNTIME_HEADROOM, string.concat(name, ": less than the required runtime headroom"));

        _assertCodeIdentity(at, name, deployed);
    }

    /// @dev The frozen EVM code identity, and the honesty of the flag that qualifies it. When the
    ///      artifact carries no immutable references the recorded keccak *is* what `EXTCODEHASH`
    ///      returns; when it does, the recorded keccak is over an artifact whose immutable slots
    ///      are still zero, so a deployed instance must present a different hash. Proving both
    ///      directions stops the flag from being set to whichever value happened to pass.
    function _assertCodeIdentity(string memory at, string memory name, address deployed) private view {
        bytes32 recorded = vm.parseJsonBytes32(_sizes, string.concat(at, ".runtime_keccak256"));
        bool isDeployedCodehash = vm.parseJsonBool(_sizes, string.concat(at, ".runtime_keccak256_is_deployed_codehash"));
        uint256 immutables = vm.parseJsonUint(_sizes, string.concat(at, ".runtime_immutable_references"));

        assertEq(isDeployedCodehash, immutables == 0, string.concat(name, ": the code-identity flag disagrees"));
        assertEq(keccak256(deployed.code), deployed.codehash, string.concat(name, ": EXTCODEHASH is not the runtime"));
        if (isDeployedCodehash) {
            assertEq(deployed.codehash, recorded, string.concat(name, ": the deployed codehash is not the frozen one"));
        } else {
            assertTrue(
                deployed.codehash != recorded,
                string.concat(name, ": an immutable-carrying artifact hash cannot equal a deployed codehash")
            );
        }
    }

    function _assertInitcode(uint256 index, string memory name, uint256 creationLength, uint256 argumentLength)
        private
        view
    {
        string memory at = string.concat(".contracts[", vm.toString(index), "]");
        assertEq(vm.parseJsonString(_sizes, string.concat(at, ".contract")), name, "frozen size row order");

        uint256 recordedCreation = vm.parseJsonUint(_sizes, string.concat(at, ".creation_bytes"));
        uint256 recordedArguments = vm.parseJsonUint(_sizes, string.concat(at, ".constructor_args_bytes"));
        uint256 recordedInitcode = vm.parseJsonUint(_sizes, string.concat(at, ".initcode_bytes"));
        uint256 margin = vm.parseJsonUint(_sizes, string.concat(at, ".initcode_margin_bytes"));

        assertEq(creationLength, recordedCreation, string.concat(name, ": creation code is not the frozen length"));
        assertEq(argumentLength, recordedArguments, string.concat(name, ": the exact constructor ABI head differs"));
        assertEq(recordedCreation + recordedArguments, recordedInitcode, string.concat(name, ": initcode does not sum"));
        assertEq(
            recordedInitcode + margin, EIP3860_INITCODE_LIMIT, string.concat(name, ": the frozen margin does not close")
        );
        assertLe(recordedInitcode, EIP3860_INITCODE_LIMIT, string.concat(name, ": exceeds EIP-3860"));

        // The recorded constructor shape and the recorded ABI head are the same fact twice: every
        // production constructor takes only 32-byte static words, so the head is exactly one word
        // per declared field.
        string[] memory shape = vm.parseJsonStringArray(_sizes, string.concat(at, ".constructor"));
        assertEq(shape.length * 32, recordedArguments, string.concat(name, ": the constructor shape and head disagree"));
    }

    /// @dev A pinned dependency build the ceremony deploys (or, for `UERC20`, that the pinned
    ///      factory deploys per launch). Same margins and same code identity as a production row.
    function _assertDependencyRuntime(uint256 index, string memory name, address deployed, bool ceremonyDeploys)
        private
        view
    {
        string memory at = string.concat(".dependency_contracts[", vm.toString(index), "]");
        assertEq(vm.parseJsonString(_sizes, string.concat(at, ".contract")), name, "frozen dependency row order");
        assertEq(
            vm.parseJsonBool(_sizes, string.concat(at, ".deployed_by_ceremony")),
            ceremonyDeploys,
            string.concat(name, ": the recorded deployment responsibility is wrong")
        );

        uint256 recorded = vm.parseJsonUint(_sizes, string.concat(at, ".runtime_bytes"));
        uint256 margin = vm.parseJsonUint(_sizes, string.concat(at, ".runtime_margin_bytes"));
        assertEq(deployed.code.length, recorded, string.concat(name, ": the deployed runtime is not the frozen length"));
        assertEq(recorded + margin, EIP170_RUNTIME_LIMIT, string.concat(name, ": the frozen margin does not close"));
        assertGe(margin, REQUIRED_RUNTIME_HEADROOM, string.concat(name, ": less than the required runtime headroom"));

        _assertCodeIdentity(at, name, deployed);
    }

    function _assertDependencyInitcode(uint256 index, string memory name, uint256 creationLength) private view {
        string memory at = string.concat(".dependency_contracts[", vm.toString(index), "]");
        assertEq(vm.parseJsonString(_sizes, string.concat(at, ".contract")), name, "frozen dependency row order");

        uint256 recordedCreation = vm.parseJsonUint(_sizes, string.concat(at, ".creation_bytes"));
        uint256 margin = vm.parseJsonUint(_sizes, string.concat(at, ".initcode_margin_bytes"));
        assertEq(creationLength, recordedCreation, string.concat(name, ": creation code is not the frozen length"));
        assertEq(
            recordedCreation + margin, EIP3860_INITCODE_LIMIT, string.concat(name, ": the frozen margin does not close")
        );
        assertLe(recordedCreation, EIP3860_INITCODE_LIMIT, string.concat(name, ": exceeds EIP-3860"));
    }
}
